### ISSUE TITLE
gulp copy file into dist folder 

### ISSUE THREAD

**Issue by ahmed-hamdy90** [gulpjs/gulp#1500] opened 2016-01-25 17:54 UTC
I knows this issue sound to be a duplicate issue But I had tired all solutions I had found into stackoverflow Questions Like [this Question](http://stackoverflow.com/questions/21224252/looking-for-way-to-copy-files-in-gulp-and-rename-based-on-parent-directory)  or closed issues  But There is nothing happened.

my folder structure :
```
project
   |_ gulpfile.js
   |_ dist/ // dist folder is does not exits but must create by using gulp copy task
   |_ client/
          |_ index.html
          |_ app/
               |_ main.js
               |_ utils/
                     |_ index.js
     
```

gulp copy task :
```
gulp.task('copy', function () {
     gulp
 	  .src('client/index.html')
 	  .pipe(gulp.dest('dist'));
});
```

I had tried to use `return`  before `gulp.src` Like This

```
gulp.task('copy', function () {
     return gulp
 	         .src('client/index.html')
 	         .pipe(gulp.dest('dist'));
});
```

And I had tried to use `base` option for `gulp.src` Like This

```
gulp.task('copy', function () {
     return gulp
 	         .src('client/index.html, {base: 'client'}')
 	         .pipe(gulp.dest('dist'));
});
```

Also I Had tried to debug `Vinyl` stream using [`gulp-debug`] (https://github.com/sindresorhus/gulp-debug) Like This:
```
gulp.task('copy', function () {
     return gulp
 	         .src('client/index.html, {base: 'client'}')
 	         .pipe(gulp.dest('dist'))
             .pipe(debug());
});
````

was print  `gulp-debug: 0 items`

**Comment by callumacrae** [comment] 2016-01-26 10:21
Can you make a repository we can test this in? Your code looks fine to me.

**Comment by ahmed-hamdy90** [comment] 2016-01-26 11:26
@callumacrae check my [`gulpfile.js`] (https://github.com/ahmed-hamdy90/explore-es6/blob/master/start%20coding%20es6%20with%20Babel/chapter02%20%5BGetting%20Started%5D/Babel%20on%20the%20Client/babel-starter/gulpfile.js) into my [project repository] (https://github.com/ahmed-hamdy90/explore-es6/tree/master/start%20coding%20es6%20with%20Babel/chapter02%20%5BGetting%20Started%5D/Babel%20on%20the%20Client/babel-starter)

**Comment by callumacrae** [comment] 2016-01-26 14:10
Try setting `base` to `__dir`. I'm not hugely experienced with this bit of node, but I _think_ it's because it's searching from the root of your project.

**Comment by heikki** [comment] 2016-01-26 14:11
I'm seeing the same thing. Renaming `chapter02 [Getting Started]` dir to `chapter02` seems make it work.

**Comment by heikki** [comment] 2016-01-26 14:16
Duplicate of #616

**Closed** 2016-01-26 14:17 UTC

**Comment by sanspot** [comment] 2018-02-21 10:52
I'm running into the same issue and I can't find a solution, I've tried all of the above, looked online as well, but I can't get it to work! I am trying to copy an HTML page from my 'src' folder to my 'dist' folder.

my project's folder structure:
`
Test
   |— dist
   |— node_modules
   |__ src
           |__ index.html
`

My Gulpfile

`
'use strict'

var gulp = require('gulp');

gulp.task('copy', function () {
    return gulp.src('./src/index.html')
        .pipe(gulp.dest('./dist/'));
});

`
I've tried removing the "return" , trying using glob (./src/**/*.html, src/*.html), I've tried using base: 'src' and 'test'... Nothing works and it's driving me nuts. 

Any ideas?

**Comment by githubad** [comment] 2018-03-22 20:48
Did anyone find any solution? Facing the same problem here.

**Comment by zikkurat** [comment] 2018-05-28 17:54
me too, any solution?

**Comment by McFarJ** [comment] 2018-06-28 21:17
Same problem here. The post that this has been marked a duplicate of is about using square brackets in a directory name, but as far as I can tell OP wasn't doing that.

**Comment by McFarJ** [comment] 2018-06-28 22:39
@doowb Hey. I just get a 404 not found page when I click the links to his repository and gulpfile.js, and I didn't see them on his page. I'll trust there's something there with square brackets though, sorry I missed it. I'll study my situation abit closer-- I'm very much a gulp n00b. Thanks.
