### ISSUE TITLE
deprecation bug

### ISSUE THREAD

**Issue by Drelcj** [gulpjs/gulp#2461] opened 2020-07-02 22:30 UTC
Before you open this issue, please complete the following tasks:

* [ ] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a bug in our code, open this issue.

### Please give us a sample of your gulpfile

```js
var gulp = require(‘gulp');

gulp.task(function () {

});
```

### Terminal output / screenshots

```sh
$ gulp
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]:
* node version (run `node -v`):
* npm version (run `npm -v`):
* gulp version (run `gulp -v`):

**Comment by ehmicky** [comment] 2020-07-03 18:42
This is a duplicate of #2460.

**Closed** 2020-07-03 18:55 UTC
