### ISSUE TITLE
gulp 4, support version for npm

### ISSUE THREAD

**Issue by robertbaker** [gulpjs/gulp#1228] opened 2015-09-02 15:45 UTC
Currently to install gulp 4, you just point npm to the 4.0 branch, which is inefficent. Every time I run npm update (which is just about every day), it pulls the gulp 4 branch even if nothing has changed.

The typescript project uses something nifty, you can install a nightly version typescript@next and the version is actually typescript@1.6.0-dev.20150902, so if I run npm update it will no longer install typescript since it has a version.

I'm not sure how to implement something like that or I would do a PR, but this would make life easier.

**Comment by callumacrae** [comment] 2015-09-02 15:49
This is a duplicate of #865

**Closed by callumacrae** 2015-09-02 15:49 UTC
