### ISSUE TITLE
FATAL ERROR: Allocation failed - process out of memory when copying to windows network share

### ISSUE THREAD

**Issue by mspace** [gulpjs/gulp#1495] opened 2016-01-22 09:33 UTC
I have next gulp task: 

```javascript
gulp.task("copy-to-share", function() {
    
  // Copying directly to server \\fileserver1\output
  // doesn't work. Therefore we need to map drive letter to network share using
  // net use l: \\fileserver1  

  return gulp.src(config.apkFile)
             .pipe(print())
             .pipe(gulp.dest("L:\output"));
});
```
When looking task manager it consumes more than 1.8 Gb and then our Continuous Integration reports: FATAL ERROR: Allocation failed - process out of memory. I'm not even sure is copying to network share supported? Running gulp from cmd, successfully copies apkFile to network share (but also needs mapped drive).

Versions: nodejs 5.0.0., gulp 3.9.0.

**Comment by contra** [comment] 2016-01-22 17:35
Does passing `{buffer: false}` as the second argument to src fix this?

**Comment by mspace** [comment] 2016-01-25 11:43
Just tried it, it does make any difference.

**Comment by phated** [comment] 2016-01-25 20:05
Pretty sure this is a duplicate of #283

**Comment by phated** [comment] 2016-01-25 20:05
Note, this is a node-glob issue that we wish they would fix.

**Closed by phated** 2016-01-25 20:05 UTC

**Comment by leggomuhgreggo** [comment] 2016-09-12 16:20
@phated hey what's the node glob issue? I'm getting an "out of memory" error as well. Thanks!
