### ISSUE TITLE
Weird behavior using gulp.watch

### ISSUE THREAD

**Issue by jsnoriegam** [gulpjs/gulp#1873] opened 2016-12-27 22:17 UTC
I created a task to watch html files and js files
The task has a ` '/**/*.js'` watcher that pass the file through babel and uglify and then send it to the dist path, and a  `'/**/*.html'` watcher that just send the file to the dist path

**What were you expecting to happen?**
The watcher should only be triggered with files that match the pattern, or perhaps if a folder that contains .js files change.

**What actually happened?**
The `'/**/*.html'` watcher works normally

The problem is that the `'/**/*.js'` watcher should only be listening to .js files but is also listening to every folder event, if  i create a folder(empty) it triggers an event and the folder is copied, and the same if i rename or delete an empty folder, the curious part is that it only happens when .js is used, i did som tests using  `'/**/*.ts'` and `'/**/*.jsx'`, and they worked normally.

```js
const SRC_PATH = 'src';
const APP_PATH = 'wwwroot/app';

gulp.task('watch', function () {
    //this is not working
    gulp.watch(SRC_PATH + '/**/*.js', function (event) {
        console.log(`${event.type}: ${event.path}`);
        gulp.src(event.path, { base: SRC_PATH })
            .pipe(babel({ presets: [['es2015', { 'loose': true }]], plugins: ['transform-es2015-modules-umd'] }))
            .pipe(uglify())
            .pipe(gulp.dest(APP_PATH));
    });
    //this is working
    gulp.watch(SRC_PATH + '/**/*.html', function (event) {
        console.log(`${event.type}: ${event.path}`);
        gulp.src(event.path, { base: SRC_PATH })
            .pipe(gulp.dest(APP_PATH));
    });
});
```

**What version of gulp are you using?**
Using gulp 3.9.1
**What versions of npm and node are you using?**
npm 4.0.5, node 6.9.2

Note: i'm using visual studio on win10 64bit (not sure if it's relevant)

**Comment by phated** [comment] 2016-12-27 22:40
Duplicate of #651 - the solution is to use the `gulp-watch` module.

**Closed by phated** 2016-12-27 22:40 UTC
