### ISSUE TITLE
Node v4.0.0 compatibility w/ Gulp 4

### ISSUE THREAD

**Issue by timkelty** [gulpjs/gulp#1250] opened 2015-09-11 13:13 UTC
Currently getting:
```
[1]    19172 segmentation fault  gulp
```

**Comment by callumacrae** [comment] 2015-09-11 13:17
Potential duplicate of #1240.

Try deleting your `node_modules` directory and reinstalling.

**Closed** 2015-09-11 13:18 UTC

**Comment by timkelty** [comment] 2015-09-11 13:22
Ah, thank you, didn't see that issue
