### ISSUE TITLE
Gulp watch issue Error: watch null EPERM

### ISSUE THREAD

**Issue by jdnichollsc** [gulpjs/gulp#1583] opened 2016-03-27 20:06 UTC
Hi guys,

Exist an issue with the **watch** method. See my gulpfile please: https://github.com/jdnichollsc/Ionic-Starter-Template/blob/master/gulpfile.js

The steps to reproduce the issue on Windows platform:
- Download the project
- Execute gulp watch in CLI
- Remove any empty folder in **./app/templates** or **./app/img**

- You can see the following error: ![Gulp issue](http://content.screencast.com/users/jdnichollsc/folders/Jing/media/a897208a-1aa1-45de-b902-c572ce0531c7/2016-03-27_1506.png)

Regards, Nicholls

**Comment by phated** [comment] 2016-03-27 20:28
Duplicate of #651

**Closed by phated** 2016-03-27 20:29 UTC

**Comment by jdnichollsc** [comment] 2016-03-27 21:01
But the issue #651 is closed, what is the solution? =)

**Comment by contra** [comment] 2016-03-27 21:15
@jdnichollsc Solution is use the gulp 4 which has a different file watcher and suffers none of these issues

**Comment by jdnichollsc** [comment] 2016-03-27 21:35
Thanks guys :+1:

**Comment by jdnichollsc** [comment] 2016-04-02 21:58
any example with Gulp 4? :)

**Comment by s100** [comment] 2016-05-20 09:54
But the latest version of Gulp is 3.9.1...?
