### ISSUE TITLE
Color support detection problem in git bash on windows

### ISSUE THREAD

**Issue by mlarcher** [gulpjs/gulp#1292] opened 2015-09-29 12:04 UTC
I recenlty update msysgit (windows version of git) from version 1.9.5 to 2.5.3. This updated the terminal it brings along (git-bash) to "GNU bash, version 4.3.42(2)-release (x86_64-pc-msys)".
I since then lost all colors from Gulp output.

Using --color as a parameter brings color back.
I assume something have changed on the way git-bash exposes its color support, and Gulp detection is not finding out the correct answer anymore.
I don't know how color support detection works in Gulp, but I can say that $TERM is exposing "xterm-256", which should be enough to assume color support.

**Comment by phated** [comment] 2015-09-29 18:45
@sindresorhus this might be something that chalk needs to know about?

**Comment by sindresorhus** [comment] 2015-09-29 18:49
That should be enough, yes. You can see the test here: https://github.com/chalk/supports-color/blob/9434c93918301a6b47faa01999482adfbf1b715c/index.js#L61

**Comment by sindresorhus** [comment] 2015-09-29 18:50
@Qix-

**Comment by Qix-** [comment] 2015-09-29 19:44
@mlarcher would you mind doing

```
$ npm i supports-color
$ node
> var s = require('supports-color');
> console.log(require('util').inspect(s));
```

in the updated console?

**Comment by mlarcher** [comment] 2015-09-29 20:19
@Qix: I confirm I only updated git, gulp didn't change version.
Here's the output you requested:
```
$ node
> var s = require('supports-color');
> console.log(require('util').inspect(s));
{ level: 1, hasBasic: true, has256: false, has16m: false }
> console.log(process.env.TERM.length, process.env.TERM);
14 'xterm-256color'
```
`has256: false` seems odd, I must say...

**Comment by Qix-** [comment] 2015-09-29 20:23
Hmm interesting. I'll take a look at the `256` though chalk as of now doesn't even support 256 colors. That should be enough for gulp to be outputting color via chalk...

@sindresorhus what do you think?

**Comment by sindresorhus** [comment] 2015-10-22 07:41
Probably related to: https://github.com/nodejs/node/issues/3006

**Comment by mlarcher** [comment] 2015-10-22 08:10
@sindresorhus, it may be, but the issue in that thread seems to be due to changes in nodeJS 4, while I'm still using node 0.12 and triggered the issue by updating only git bash. Both could have the same underlying cause, though.

**Comment by phated** [comment] 2015-11-09 20:59
@mlarcher @sindresorhus what was the outcome for this issue?

**Comment by mlarcher** [comment] 2015-11-09 21:24
@phated It's still ongoing afaik. Probably not on top of priorities, though.
For my part I still use --color after each gulp command for now :|

**Comment by MobiusHorizons** [comment] 2016-01-06 20:29
I can confirm that this is an issue.

**Comment by Qix-** [comment] 2016-01-06 21:35
[This comment](https://github.com/nodejs/node/issues/3006#issuecomment-164259466) mentions the same issue. This is a node problem, not a Chalk problem.

What appears to be happening is `supports-color`, the module we wrote to check to see if the terminal supports color, is seeing that `isatty()` is returning that the terminal session is not actually a terminal session, but a pipe or something. That's [Node's fault](https://github.com/nodejs/node/issues/3006).

From there, chalk is told _not_ to use colors, hence not getting any colored output.

Unfortunately there isn't much we can do other than to advise using `--color` or the environment variable `FORCE_COLOR` to run what you need inside of MSys or Cygwin (not sure if this affects Cygwin but it very well might).

**Comment by phated** [comment] 2016-01-14 00:46
@Qix- what would happen if we set `process.env.FORCE_COLOR = true` for every instance inside the CLI?

**Comment by Qix-** [comment] 2016-01-14 05:29
Well if you have any processes piping to each other that don't take into account ANSI output you might have a problem there. Build systems and ANSI output from child processes can get tricky pretty quickly.

**Comment by phated** [comment] 2016-04-05 02:38
Looks like this is a Git for Windows problem and can be resolved by following the comment at https://github.com/nodejs/node/issues/3006#issuecomment-171129702

Closing this as it is something we can't control.

**Closed by phated** 2016-04-05 02:38 UTC
Labels: further investigation required, gulp-cli, missing information

**Comment by yairEO** [comment] 2016-11-03 08:56
Was helped in another thread and set a windows system variable `FORCE_COLOR` to `true`, did not restart, and now I have colors in Git Bash (windows 7)

**Comment by griest024** [comment] 2017-09-27 04:46
In windows 8.1 a system environment variable did not work, but adding `export FORCE_COLOR=true` to `.bashrc` did the trick.

**Comment by phated** [comment] 2017-10-01 20:56
Btw, with changes happening in gulp-cli, there will no longer be a check for supports-color and if color is not supported, the user will have to add `--no-color` to their command.

**Comment by plroebuck** [comment] 2018-12-02 11:29
For what it's worth, `FORCE_COLOR` value should be numeric string, not `true`.

For shell users, if you export the value (as below), _all_ commands run by the shell will be colorized 
```sh
$ export FORCE_COLOR="1"    # Force terminal escape colors for ALL commands to follow...
$ gulp
```
You can also enable colors for a _single_ command à la
```sh
$ FORCE_COLOR="1"  gulp
```
Disabling colors works similarly, here disabling color support for a _single_ command.
```sh
$ FORCE_COLOR="0" gulp
```

**Comment by rakeshshubhu** [comment] 2019-12-21 06:14
is this still the problem on git bash?

**Comment by Thorocaine** [comment] 2022-06-30 15:09
I have this problem, using git bash on Windows Terminal...

    ←[032mâo" Generated
etc...
