### ISSUE TITLE
Gulp can't generate new files on Windows 7

### ISSUE THREAD

**Issue by Clunt** [gulpjs/gulp#940] opened 2015-03-03 09:51 UTC
nodejs v0.10.36
gulp v3.8.10
```
var gulp = require('gulp');
gulp.task('default', function() {
  return gulp.src('main.css').pipe(gulp.dest('style/'));
});
```
When I run `gulp`,Nothing can be found

**Comment by callumacrae** [comment] 2015-03-03 09:58
Does main.css exist in the same directory as the gulpfile?

You can check whether a glob is matching using [gulp-debug](https://www.npmjs.com/package/gulp-debug).

**Comment by phated** [comment] 2015-03-14 03:13
Either duplicate of #374 or a support question.  Support questions should be directed to http://stackoverflow.com/questions/tagged/gulp

**Closed by phated** 2015-03-14 03:13 UTC

**Comment by Clunt** [comment] 2015-03-25 10:15
Thanks for you reply, I use mac now and it works.
