### ISSUE TITLE
Old version of lodash module in use

### ISSUE THREAD

**Issue by ryanlelek** [gulpjs/gulp#1482] opened 2016-01-10 07:14 UTC
I'm getting significant warnings from NPM when installing and have narrowed it down to the Gulp module.
These break the deployment process since NPM returns a non-0 exit code.
Submitting for a sanity check and suggestions, then maybe a fix.

1) gulp, v3.9.0 added to package.json as the only module in dependencies
2) `rm -rf node_modules/ && npm install --production`
3) NPM warning `npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`
4) ` grep -r 1.0.2 node_modules/gulp/** | grep lodash` seems to show it in vinyl-fs

**Comment by vlizard** [comment] 2016-01-10 07:42
Duplicate of #1295 and many others.

**Comment by phated** [comment] 2016-01-10 08:49
Please use the github search feature and avoid submitting duplicates.

**Closed by phated** 2016-01-10 08:49 UTC

**Comment by ryanlelek** [comment] 2016-01-10 19:20
Yep, my fault. When I searched for "lodash" I didn't include closed issues.

**Comment by TrySound** [comment] 2016-01-10 19:22
@phated Let's keep at least one "lodash" issue open. This can prevent tones of the same issues in the future.

**Comment by phated** [comment] 2016-01-10 19:32
@TrySound leaving them open doesn't help, we have the same problem with issues we still keep open. And leaving it open seems like it is a real issue...

**Comment by callumacrae** [comment] 2016-01-10 21:30
Could have a PSA-type issue created by one of us, saying that we know about it and linking to a couple of the older issues

**Comment by phated** [comment] 2016-01-11 23:46
@callumacrae good idea, opened at #1485

**Comment by phated** [comment] 2016-01-11 23:46
Locking this to keep everything focused on the [Notice] issue.
