### ISSUE TITLE
not support node22

### ISSUE THREAD

**Issue by yuu2lee4** [gulpjs/gulp#2798] opened 2024-04-27 10:57 UTC
Before you open this issue, please complete the following tasks:

* [ ] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [ ] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [ ] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?
work with node22
### What actually happened?
not work with node22
### Please give us a sample of your gulpfile

```js
import gulp from 'gulp'
import uglify from 'gulp-uglify'

gulp.task('minify-js', function () {
  return gulp.src('assets/*.js')
    .pipe(uglify())
    .pipe(gulp.dest('dist/assets'))
})
```

### Terminal output / screenshots

![image](https://github.com/gulpjs/gulp/assets/8046366/ebfc9efb-7acc-415e-a896-aeb3f477825c)

```sh
$ gulp
```

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Macos 12.7.4
* node version (run `node -v`):22.0.0
* npm version (run `npm -v`):10.5.1
* gulp version (run `gulp -v`): CLI version: 3.0.0  Local version: 5.0.0

**Comment by phated** [comment] 2024-04-27 16:15
Duplicate of https://github.com/gulpjs/vinyl-fs/issues/350

This is a bug in node that is being fixed upstream.

**Closed by phated** 2024-04-27 16:15 UTC
