### ISSUE TITLE
Foundation 6 - Only first change in the src folder is watched

### ISSUE THREAD

**Issue by grosewarne** [gulpjs/gulp#1623] opened 2016-04-29 08:43 UTC
I am using foundation 6.2
With the [lastest update ](https://github.com/gulpjs/gulp/commit/6c03475e1a39d18c139b4d56baa1c14a587f9f4a)
Only first change in the src folder is watched after that it stops.
It serve only first change, and ends with "Reloading Browsers..."

**Comment by alexandru-calinoiu** [comment] 2016-04-29 12:26
I have the same issue but with a stylus compile task, when the compilation fails gulp will exit.

**Comment by phated** [comment] 2016-04-29 18:31
Can someone please tell them to stop suggesting using the new-docs branch?  That is a terrible suggestion.  I'm not going to create an account there.

**Comment by phated** [comment] 2016-04-29 18:55
Alright, I tracked down the first issue (haven't investigated @alexandru-calinoiu's since you clumped it together in this issue).  @grosewarne the way foundation-zurb-template is using `browser.reload` is incorrect and the only reason it was working in the first place was some inconsistencies in gulp.  With the switch to `glob-watcher` version 3, we have normalized the behavior and now all watch tasks are async; however, foundation-zurb-template is using a sync `browser.reload` call as a "task".

**Comment by phated** [comment] 2016-04-29 19:02
@grosewarne https://github.com/zurb/foundation-zurb-template/pull/37 please inform whoever to merge that and use my fork/changes until it is merged.

**Comment by phated** [comment] 2016-04-29 19:03
@alexandru-calinoiu your problem doesn't exist for me when using the same changes I PRed for @grosewarne's problem.  Not sure if that's what solved it or if you have something else going on.

Closing this.

**Closed by phated** 2016-04-29 19:03 UTC

**Comment by alexandru-calinoiu** [comment] 2016-05-03 13:22
@phated not sure what the problem is just yet.
