### ISSUE TITLE
gulp.watch with **/*.js and multiple globs not working on Windows

### ISSUE THREAD

**Issue by adambuczynski** [gulpjs/gulp#1491] opened 2016-01-18 01:55 UTC
When watching files with Gulp 4, I have the following watch:

```js
gulp.watch(['app/**/*.js', 'app/components/**/*.html']);
```

On OS X, it works fine for both JS and HTML files, but on Windows 7, making a file change to a JS file does not get detected.

Changing this to the following fixes the issue:

```js
gulp.watch(['app/**/*']);
```

Also, watching *only* JS files also works as intended:

```js
gulp.watch(['app/**/*.js']);
```

It seems only the combination of both globs breaks something causing JS files not to be watched on windows.

Possibly related to https://github.com/floatdrop/gulp-watch/issues/194

**Comment by contra** [comment] 2016-01-18 04:03
Can you try gulp 4.0 which has a new file watcher that fixes these bugs?

**Comment by adambuczynski** [comment] 2016-01-18 04:04
@contra This is with Gulp 4.

**Comment by contra** [comment] 2016-01-18 11:13
@adambuczynski Are you able to reproduce these issues using chokidar directly? If so, open the issue there and LMK

**Comment by adambuczynski** [comment] 2016-01-18 18:19
Will check. Problem is I don't have access to the windows computer directly, as I was helping someone else getting the build process up and running on their windows machine remotely. However, I will try to reproduce with chokidar directly.

**Comment by adambuczynski** [comment] 2016-01-19 00:09
@contra Have tested with a simple example, just chokidar v1.4.2:

```js
var chokidar = require('chokidar');
chokidar.watch(['app/**/*.js', 'app/components/**/*.html']).on('all', (event, path) => {
  console.log(event, path);
});
```

Folder structure:
![ss](https://www.dropbox.com/s/hogqy8dsz3a6lga/Screenshot%202016-01-19%2012.44.18.png?dl=1)

Result is that change detection *does* work with just chokidar, for both HTML and JS files:

![ss](https://files.gitter.im/liatreis/cgqm/blob)

So it seems to be a gulp issue (unless gulp uses an older version of chokidar which was bugged)

**Comment by phated** [comment] 2016-01-19 04:33
Please test "change", "unlink" and "add" events, as those are the chokidar events we listen to.

**Comment by adambuczynski** [comment] 2016-01-19 07:14
As I said, I don't have direct access to the Windows computer, and I feel I've already exhausted them with asking them to test it with just Chokidar. 

I've taken a look at the Gulp 4 source code and I don't see anything that could cause the issue, so I'm at a bit of loss here. Using chokidar directly seems to work fine.

I'll try to devise another isolated test case with both gulp and chokidar and will report back once I know more.

**Comment by adambuczynski** [comment] 2016-01-27 22:09
Is anyone else with access to a windows 7 computer able to reproduce this?

**Comment by thasmo** [comment] 2016-02-14 20:53
I could test this on Windows 10. May I ask you to provide a full example of how you do it with Gulp 4? Thanks!

**Comment by adambuczynski** [comment] 2016-02-14 22:01
@thasmo you can find a "full" example in this Angular 1 seed project: https://github.com/meanie/angular-seed

Should be good to go out of the box after `npm install`. Run `npm start` to fire up the dev environment, which will run the gulp watch as well as serve the client via Browser sync.

**Comment by thasmo** [comment] 2016-02-14 23:54
Tried it and seems like `app/**/*.js` gets ignored i.e. not watched, although I didn't have a closer look because the project's build setup is rather complex. Could it be that `app/components/**/*.html` somehow overwrites or invlidates `app/**/*.js`?

**Comment by adambuczynski** [comment] 2016-02-15 02:10
It shouldn't, it's working for me, but I'll do a fresh install when I'm back home and have another look.

The constants for the files are both arrays, and they get merged in the watch task, which then gets passed as an array to gulp.watch;

```js
let files = [].concat(APP_JS_SRC, APP_HTML_SRC);
gulp.watch(files, debounce(
  gulp.series(lint, buildAppJs, buildIndex), WATCH_DEBOUNCE_DELAY
));
```

**Comment by adambuczynski** [comment] 2016-02-15 19:10
I've installed the angular seed and tested, and on OS X the watches are working correctly. So in your case @thasmo, when you run the project and make changes to HTML files in the `app/components` folder, does the watch get triggered? How about for js files?

**Comment by thasmo** [comment] 2016-02-15 21:27
That's what I meant. Changing HTML gets triggered correctly, JS changes are **not** picked up.

**Comment by adambuczynski** [comment] 2016-02-15 22:07
Ok do basically that confirms that you can replicate the issue on Windows 10. What if you create this simple example with chokidar only? https://github.com/gulpjs/gulp/issues/1491#issuecomment-172689471

Could it be that creating multiple watchers is what's affecting chokidar? Maybe if another watcher negates files listed in a previous watcher it somehow overrides / merges the rules? I'll create another test setup for that.

**Comment by adambuczynski** [comment] 2016-02-15 23:27
@thasmo could you check with these two test scripts on windows and see what console output you get when you edit the `test.js` and `test.html` files?

Folder/file structure:

![image](https://cloud.githubusercontent.com/assets/490562/13062998/53d7fa70-d4a8-11e5-8ee9-d34b92e5861f.png)

package.json:

```json
{
  "name": "chokidar-gulp-test",
  "version": "1.0.0",
  "description": "Simple test",
  "author": "Adam Buczynski",
  "license": "ISC",
  "dependencies": {
    "chokidar": "^1.4.2",
    "gulp": "gulpjs/gulp#4.0"
  }
}
```

chokidar.js:

```js
'use strict';

const APP_JS_SRC = ['app/**/*.js'];
const APP_HTML_SRC = ['app/components/**/*.html'];
const LIB_JS_SRC = ['lib/**/*.js'];

let appFiles = [].concat(APP_JS_SRC, APP_HTML_SRC);
let libFiles = LIB_JS_SRC;

let chokidar = require('chokidar');
chokidar.watch(appFiles).on('all', (event, path) => {
  console.log('app file:', event, path);
});
chokidar.watch(libFiles).on('all', (event, path) => {
  console.log('lib file:', event, path);
});
```

gulp.js

```js
'use strict';

const APP_JS_SRC = ['app/**/*.js'];
const APP_HTML_SRC = ['app/components/**/*.html'];
const LIB_JS_SRC = ['lib/**/*.js'];

let appFiles = [].concat(APP_JS_SRC, APP_HTML_SRC);
let libFiles = LIB_JS_SRC;

function doAppStuff() {
  console.log('app file changed');
}
function doLibStuff() {
  console.log('lib file changed');
}

let gulp = require('gulp');
gulp.watch(appFiles, doAppStuff);
gulp.watch(libFiles, doLibStuff);
```

Then test both separately with:

`node chokidar.js`
`node gulp.js`

Do the console logs get triggered properly whenever you make file changes for both the chokidar and gulp scripts?

**Comment by replete** [comment] 2016-02-20 19:55
I've had some weird issues which were all down to missing Windows packages. Try this:

* Ensure `node-gyp` has no errors with missing headers/libs
 1. Open `File > New > Project` in VS2015
 2. Browse `Other Languages > C++`
 3. Select `Install Visual C++ 2015 tools for Windows Desktop`, hit OK, install (Adds Visual C++ libs and Windows 8.1 SDK)

**Comment by RobVanGroenewoud** [comment] 2016-03-03 12:21
@adambuczynski: I just checked your proposed code on Windows 7.
Both chokidar and gulp are receiving the event properly.

fwiw: I do have Visual Studio 2015 installed.

**Comment by adambuczynski** [comment] 2016-03-03 19:38
@RobVanGroenewoud thanks for checking, I will try to do some more debugging on the specific machine where it's failing.

**Comment by puranjayjain** [comment] 2016-03-30 06:17
@RobVanGroenewoud I'm also facing he same issue as yours but on windows 10 x64, @adambuczynski unfortunately your code didnt work out for me here :sob: any suggestions anyone?

**Comment by adambuczynski** [comment] 2016-03-31 02:15
@puranjayjain sorry, not sure how to debug this, as I don't have access to windows. And quite frankly, since I only work on Mac myself, this issue doesn't impact me much so I don't want to spend too much more time on it.

If this comes back to bite me again some time I might spend some more time analysing it, but for now I wouldn't know what to do about it.

**Comment by jimmythomson** [comment] 2016-04-01 12:54
@adambuczynski - all works fine for me on Windows 7 Enterprise SP1. For reference, I have VS2012 installed. I'll test on a Windows 7 Professional machine this evening (without VS).

**Comment by phated** [comment] 2016-04-05 03:57
Copying @es128 here.  Maybe he has some insights

**Comment by adambuczynski** [comment] 2016-05-26 23:30
@phated I have now started to experience this exact same problem on OS X 10.11.2.
With the following watch in place:

```js
gulp.watch(['app/**/*.js', 'app/components/**/*.html']);
```

If I make changes to a `.js` file in `app/components` gulp watch is *not* triggered.
If I make changes to a `.html` file in `app/components` *or* changes to a `.js` file in `app/somethingElse`, gulp watch is triggered.

It seems that the glob for `.html` files is somehow preventing `.js` files in the same folder from being watched.

Not sure if this is a gulp-watch problem or an issue with the underlying glob-watcher.

**Comment by phated** [comment] 2016-05-26 23:50
@adambuczynski if you are using gulp 4 with the function syntax, you probably aren't using a proper async function, which is a different issue (many duplicates).

**Comment by adambuczynski** [comment] 2016-05-26 23:53
@phated not sure what you mean, I have been using the same code for months now, and it's always worked well.

```js
let files = [].concat(APP_JS_SRC, APP_HTML_SRC);
  gulp.watch(files, debounce(
    gulp.series(lint, buildAppJs, buildIndex), WATCH_DEBOUNCE_DELAY
  ));
```

The debounce is in there because at the time you hadn't included that in glob-watcher yet. If that's been updated I can probably remove those now.

**Comment by phated** [comment] 2016-05-26 23:55
@adambuczynski that's because debounce functionality wasn't introduced into gulp 4 yet.  I'm guessing you just updated.  You watch functions must signal async completion now.  The docs were written this way for a long time but no one was writing code this way but there were subtle bugs that allowed it to work.  This functionality has been normalized now (tasks & watch require the same async completion).

**Comment by adambuczynski** [comment] 2016-05-26 23:58
@phated Yes, I recently updated gulp. Does that mean I can get rid of the manual debouncing now? 
I'll remove them and double check the task functions.

**Comment by phated** [comment] 2016-05-27 00:08
@adambuczynski yeah, you can remove the manual debouncing and if you keep the `gulp.series` call, everything should just work because it returns an async function.

**Comment by adambuczynski** [comment] 2016-05-27 00:13
@phated Unfortunately, it doesn't seem to work. Still has the same problem.

Setup is now:

```js
let files = [].concat(APP_JS_SRC, APP_HTML_SRC);
gulp.watch(files, gulp.series(lint, buildAppJs, buildIndex));
```

Only when I explicitly add `app/components/**/*.js` to the globs does it detect file changes in those JS files. If I leave that bit out and only watch `app/**/*.js` it doesn't detect them.

I will make an isolated test case.

**Comment by WestonThayer** [comment] 2016-06-09 00:43
+1, I repro this on Windows 10, x64. Any way I can help?

**Comment by adambuczynski** [comment] 2016-06-09 01:56
I have been unsuccessful so far in creating an isolated test case and just added the sub directory to my globs to get around this issue. However @WestonThayer if you are also experiencing this, maybe we can figure out together what's causing it.

Have you been able to reproduce this consistently with an isolated test case?

**Comment by WestonThayer** [comment] 2016-06-15 22:52
I debugged it a bit, turns out that it's not actually hung, gaze.js is just taking a long time to watch ~2,000 files. I got tricked because the first glob I tested with only turns up 10 files, thus it didn't hang with just that one. Then I added the second glob, which targeted close to 2,000, so that caused the hang.

My scenario is to watch all asset-type files (.png, .jpg, etc) for updates, then copy them to my build/ directory. I do have thousands. Is there a better way to go about this?

**Comment by contra** [comment] 2016-06-16 00:13
@WestonThayer Use gulp 4.0 which has a better globbing engine (chokidar)

**Comment by WestonThayer** [comment] 2016-06-16 19:48
I see that's not on npm yet. What's the best way to consume it?

**Comment by adambuczynski** [comment] 2016-06-16 19:52
@WestonThayer 

https://demisx.github.io/gulp4/2015/01/15/install-gulp4.html

**Comment by phated** [comment] 2016-06-28 23:48
I'm going to be closing this as it doesn't seem to be reproducible.  We hand everything off to `chokidar`, so if it crops up again, it will probably need to opened over there.

**Closed by phated** 2016-06-28 23:48 UTC
Labels: further investigation required, gulp4, help wanted

**Comment by adambuczynski** [comment] 2016-06-29 00:40
Well, I have given up on trying to debug this and resorted to just specifying the components path in the folders to watch. It's not pretty, but at least it works :(

It's also worth noting that for some new Angular 2 projects we've been migrating away from Gulp to Webpack, and haven't been experiencing issues like these there yet. I believe Webpack also uses Chokidar to watch for file changes.

**Comment by phated** [comment] 2016-06-29 00:51
@adambuczynski webpack doesn't operate on globs :/

**Comment by mmfilesi** [comment] 2016-09-21 16:05
Thats work (window 10, browserSync).

```
gulp.task('build', gulp.parallel('prepareScripts', 'prepareStatics', (done)=> {
    done();
}));
gulp.task('server', ()=> {
  browserSync.init(optionsServer);
  gulp.watch(baseSrc + '/**/*.js').on('change', gulp.series('build', browserSync.reload));
});

```

**Comment by phated** [comment] 2016-09-21 20:19
@mmfilesi that is definitely a hacky and incorrect way to work around this.  Just wrap `browsersync.reload` into an async function to do it the correct way.

**Comment by callumacrae** [comment] 2016-09-22 08:22
@phated: The `browsersync.reload` function is designed to be used like that: https://www.browsersync.io/docs/gulp

That said, not sure if it's a good idea still.

**Comment by phated** [comment] 2016-09-22 08:57
@callumacrae incorrect since we changed the way watch behaves (to bring it inline with task completion behavior).

**Comment by callumacrae** [comment] 2016-09-22 09:00
Fair enough. @shakyShane are you able to update those docs?

**Comment by seantw** [comment] 2018-07-10 05:13
There is no better way than require('gulp-watch') under Windows!

**Comment by guillegr123** [comment] 2019-04-10 20:16
It seems to be a chokidar issue after all, when mixing windows-style paths and globs. See: https://github.com/paulmillr/chokidar/issues/777

**Comment by mattpr** [comment] 2021-05-14 10:27
I know this is an old issue but since I have been running into it on MacOS with gulp latest I figured I would post here for other googlers.  

I've been running into this on MacOS and I suspect it related to changes in gulp4, in particular that `gulp.watch` really needs an async function or it will only run once (https://gulpjs.com/docs/en/getting-started/watching-files/#warning-avoid-synchronous).

It appears to be caused by either using the following pattern (where `copy` is synchronous)...

```javascript
function copy () {
    var newer = require('gulp-newer');
    return gulp.src([srcDir+'/**/*'])
        .pipe(newer(destDir))
        .pipe(gulp.dest(destDir));
}
function watch () { 
    gulp.watch(srcDir+'/**/*', copy);    // copy is synchronous, so wrap in gulp.series(copy) to fix
}
module.exports.watch = watch;
```

or this pattern...

```javascript
function copy () {
    var newer = require('gulp-newer');
    return gulp.src([srcDir+'/**/*'])
        .pipe(newer(destDir))
        .pipe(gulp.dest(destDir));
}
function watch (done) { 
    gulp.watch(srcDir+'/**/*', copy);    // copy is synchronous
    return done();
}
module.exports.watch = watch;
```

...or some combination of the two.  I didn't dig in further but updating my `watch` code to match the example [here](https://gist.github.com/jeromecoupe/0b807b0c1050647eb340360902c3203a) seems to have resolved the issue...

```javascript
function copy () {
    var newer = require('gulp-newer');
    return gulp.src([srcDir+'/**/*'])
        .pipe(newer(destDir))
        .pipe(gulp.dest(destDir));
}
function watch () { 
    gulp.watch(srcDir+'/**/*', gulp.series(copy));    // copy is synchronous, so wrap in gulp.series(copy)
}
module.exports.watch = watch;
```

I also found some bugs in my some gulp watch code on my end that hadn't gotten fully updated from gulp3 and had stuff like `gulp.watch(srcDir+'/**/*', gulp.task('old-task-name'))`...of course `old-task-name` doesn't exist anymore in gulp registry.  The interesting bit was there was no warning/complaint about referencing (trying to retrieve) a task by name from the task-registry that doesn't exist (anymore).  Might be helpful for people migrating from gulp3 to output some helpful warnings/errors when using the deprecated `task` api.
