### ISSUE TITLE
Duration is hidden in Powershell on Windows with standard background color

### ISSUE THREAD

**Issue by No0Vad** [gulpjs/gulp#2271] opened 2018-12-16 13:24 UTC
**What were you expecting to happen?**
The duration to be visible.

**What actually happened?**
Duration is in the same color as powershells standard background color, so it is not visible.

With the --no-color flag
![image](https://user-images.githubusercontent.com/9308455/50053971-23658780-013d-11e9-8100-c18dd0071fbf.png)

With color
![image](https://user-images.githubusercontent.com/9308455/50053993-5445bc80-013d-11e9-9820-7a02a961a5ac.png)

Using the same color as the taskname would solve it.

**Please post a sample of your gulpfile (preferably reduced to just the bit that's not working)**
N/A

**What version of gulp are you using?**
Version v4.0.0

**What versions of npm and node are you using?**
NPM v6.5.0
Node v10.14.2

**Comment by phated** [comment] 2018-12-16 21:51
Duplicate of https://github.com/gulpjs/gulp-cli/issues/63 and https://github.com/gulpjs/fancy-log/issues/18

This is a WIP but we don't have an ETA.

**Comment by craxal** [comment] 2019-06-05 17:06
It's not just with the default PowerShell window colors. I modified my colors, and the duration is still invisible (with gulp@4.0.2).

![image](https://user-images.githubusercontent.com/3473026/58975156-2733a780-8779-11e9-8e00-4fc8513c0c27.png)

**Comment by phated** [comment] 2024-03-23 04:08
Support for theming timestamps and messages was added to gulp-cli in https://github.com/gulpjs/gulp-cli/pull/260. This will be released as gulp-cli v3.0.0 and included in the gulp v5 release. As with all gulp-cli releases, newer versions can run older gulp so you'll be able to theme anything with v3.0.0

**Closed by phated** 2024-03-23 04:08 UTC
Labels: enhancement, help wanted
