### ISSUE TITLE
Deprecated packages in npm install

### ISSUE THREAD

**Issue by TJProgrammer** [gulpjs/gulp#1786] opened 2016-09-01 19:23 UTC
Hello.
When I installed `gulp`, I have received these messages:
```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs
@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
```
This issue is only for check if these dependencies are important for gulp system.
Thanks.

**Comment by Arial7** [comment] 2016-09-01 19:36
Please use the search function before opening an issue. This has been discussed many many times.

**Comment by contra** [comment] 2016-09-01 19:36
Please use the search before opening issues, this is a duplicate of ~100 other issues.

**Comment by contra** [comment] 2016-09-01 19:37
To answer the question though: it doesn't really matter, they're just warnings. When gulp 4.0 comes out it will use the latest versions, but these updates are breaking changes so don't expect them in the 3.x release.

**Closed** 2016-09-01 19:36 UTC

**Comment by TJProgrammer** [comment] 2016-09-03 08:18
Thanks.
