### ISSUE TITLE
gulp.watch not watch new fold after run

### ISSUE THREAD

**Issue by iahu** [gulpjs/gulp#1603] opened 2016-04-15 03:07 UTC
I run a `gulp watch` task `gulp.watch('./src/css/**/*.less', ['build-css']);` to build less.
Today, I create a new fold `./css/less/`, and a new less file `./css/less/a.less`.

The `gulp watch` task not run after I save my a.less. I try to kill the watch task and re-run it, this time it works.

Hope gulp can support new fold after run.

Thanks.

**Comment by phated** [comment] 2016-04-15 18:54
In gulp 3, the file watcher has a ton of problems (duplicate of #651).

In gulp 4, this would be a chokidar issue.

Which are you using?

**Comment by iahu** [comment] 2016-04-16 01:52
I use gulp 3.

**Comment by jonhkr** [comment] 2016-04-17 02:57
I have a problem that may be related, here are the steps to reproduce:
- Add a new folder `test` in a watched directory `[project]/src`
- Remove the folder `test` that was just added
- Add a new file in the watched directory `[project]/src`

Boom, I get this error:

```
Error: watch [project]/src/test ENOENT
    at exports._errnoException (util.js:856:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at Gaze._watchDir ([project]/node_modules/gaze/lib/gaze.js:289:30)
    at [project]/node_modules/gaze/lib/gaze.js:358:10
    at iterate ([project]/node_modules/gaze/lib/helper.js:52:5)
    at [project]/node_modules/gaze/lib/helper.js:61:11
    at [project]/node_modules/gaze/lib/gaze.js:420:5
    at iterate ([project]/node_modules/gaze/lib/helper.js:52:5)
    at [project]/node_modules/gaze/lib/helper.js:61:11
```

**Comment by phated** [comment] 2016-04-18 18:33
The gulp 3 file watcher has an insane amount of bugs.  Closing this as a duplicate of #651 - either update to gulp 4 or use a better file watcher directly (like chokidar).

**Closed by phated** 2016-04-18 18:33 UTC
