### ISSUE TITLE
Tasks tree generated incorrectly when registering a fn more than once

### ISSUE THREAD

**Issue by mikehaas763** [gulpjs/gulp#1223] opened 2015-08-31 12:51 UTC
With gulp 4 I have the following gulp file.

```javascript
'use strict';

var gulp = require('gulp');
var serveWebApplication = require('./gulp/serveWebApplication');
var cleanBuild = require('./gulp/cleanBuild');
var buildTasks = require('./gulp/buildTasks');

gulp.task('build', buildTasks);
gulp.task('clean', cleanBuild);
gulp.task('serve', gulp.series(buildTasks, serveWebApplication));

// At this time there are no build differences between environments
// but these are needed for a CI pipeline.
gulp.task('dev', buildTasks);
gulp.task('qa', buildTasks);
```

Notice that I've registered the buildTasks function (itself a gulp.series() function) three times because my company's build pipeline expects those task names (dev and qa). This causes the top level of the tasks output names to be overridden to whichever name is registered for that function last. So in this case the output is like this:

qa
clean
serve
qa
qa

I **can** actually start the tasks by their names it's just the output tree that's messed up (`gulp dev` and `gulp qa` both work).

I can get around this by either wrapping each buildTasks reference in gulp.parallel or by just creating new qaBuildTasks or devBuildTasks functions. I suspect the tree I'm getting though is not really what's expected.

**Comment by phated** [comment] 2015-08-31 18:07
Duplicate of #1159

**Closed by phated** 2015-08-31 18:07 UTC
