### ISSUE TITLE
Overriding a task after a dependant task has been declared does not update the dependant task

### ISSUE THREAD

**Issue by fluffynuts** [gulpjs/gulp#2337] opened 2019-05-30 06:50 UTC
**What were you expecting to happen?**

I expected that registering an override for a dependency task would update all dependants, as it used to under gulp 3

**What actually happened?**

I have a base set of tasks which a consuming project can import and a `gulpfile.js` which uses `require-dir` to pull in those tasks and then pull in local overrides from a local tasks folder; to illustrate: 
- first I `require-dir` on the `gulp-tasks` folder, which contains some task definitions in separate .js files
- then I `require-dir` on the `local-tasks` folder (if available) and pull in any tasks there -- tasks there are purposely allowed to override base tasks by name, which works as expected for top-level tasks (and used to work for dependencies under gulp 3)

The idea is that for 90% of the time, there should be zero-conf to use gulp for building, testing, packing and potentially deploying .net projects.

It's worked fairly well for some time, and I've taken the leap to upgrade to gulp4, which is generally working quite well.

What I have noticed though, is that dependencies which are overridden in local tasks don't seem to make it to their dependants. An example illustrates, with `gulp-tasks` being the source of base tasks and `local-tasks` being locally-provided tasks:
- `gulp-tasks` has a `pack` target which packs up any .nuspec files into nuget packages
- `local-tasks` has a `deploy` task which depends on `pack`: once a nuget package has been created, it can be deployed to the nuget feed
- `local-tasks` overrides the `pack` task because it has a different way of calculating the nuget package version: the base `pack` task simply uses the version specified in the nuspec file, where the override creates a version based on the date-time, Jenkins build number and SHA of the git commit for the package

What I'm seeing is that if I just run `gulp pack`, the override task is run -- so the original `pack` task was specified, then overridden from `local-tasks`. All good.

When I run `gulp deploy`, the _original_ pack task is run, not the override, and I have to assume that what's happening under the covers (due to `require-dir` loading the local `deploy` before the local `pack`) is this:
- `pack` from `gulp-tasks` is registered
- `deploy` from `local-tasks` is registered, depending on a _reference_ to the original `pack` task
` `pack` from `local-tasks` is registered, so becomes available as the top-level `pack` task, but _does not_ override the dependency for the `deploy` task

The result is that if I `pack` at top-level, I get the correct output for my package. If I `deploy` at the top-level, I get the incorrect version for my package because the override `pack` task is not run.

An example to reproduce the issue can be found here: https://github.com/fluffynuts/gulp-dependency-overrides
- run `npm run gulp pack` to see the override is run
- run `npm run gulp deploy` to see that the original `pack` is run instead

**What version of gulp are you using?**
package.json says: ^4.0.2

**What versions of npm and node are you using?**
`npm --version` -> 6.4.1
`node --version` -> v10.15.3

**Comment by doowb** [comment] 2019-05-30 13:39
I took a look at your repo and I see you're using `gulp.series('pack')` to specify the dependency. The way `gulp.series` works is that it gets the task specified and creates a new function that is passed into the `gulp.task` method.

One way you could try solving this is by changing your code to something like this:

```js
gulp.task('deploy', (...args) => gulp.series('pack')(...args), () => {
    console.log('deploy task called');
    return Promise.resolve();
});
```

I'm inlining the dependencies function here to show that the function you create is passed in as a dependency, then that uses `gulp.series` to create a function to call inside it.

To make this a little easier to use for other situations, you can create a function to help with creating those dependencies:

```js
const dependencies = (...tasks) => {
  return (...args) => gulp.series(...tasks)(...args);
};

gulp.task('deploy', dependencies('pack'), () => {
  console.log('deploy task called');
  return Promise.resolve();
});
```

I hope this helps.
I'm going to close this issue since it's a support question and not a bug.

**Closed by doowb** 2019-05-30 13:39 UTC

**Comment by fluffynuts** [comment] 2019-05-31 08:05
Thanks, that does indeed help (:
