### ISSUE TITLE
gulp.watch can't notice when you add new file/folder or delete

### ISSUE THREAD

**Issue by shafaiatul** [gulpjs/gulp#1184] opened 2015-08-03 03:48 UTC
To fix this issue, chokidar is the best solution. To read more about it https://www.npmjs.com/package/chokidar

If anybody comes across the same issue, this npm module will you out. 
Good luck.

**Comment by phated** [comment] 2015-08-03 04:32
Duplicate of #651

**Closed by phated** 2015-08-03 04:32 UTC
