### ISSUE TITLE
gulp.watch('app/app.js') seems to be watching for more than that file

### ISSUE THREAD

**Issue by matikun86** [gulpjs/gulp#1514] opened 2016-02-04 20:11 UTC
Hi, I've found some strange behavior with watch.
In my gulpfile besides watching files for changes I'm doing validation, etc. And I had troubles with some `watch` being fired multiple times when it wasn't supposed to. So I've narrowed it down to having this in my code:

```Javascript
gulp.watch([
  'app/app.js'
]).on('change', function(event) {
  console.log('File ' + event.path + ' was ' + event.type);
});
```

And looking at the console I'm getting messages like:

File c:\<myproject>\app\tmp was deleted
File c:\<myproject>\app\tmp\partials\ was renamed
File c:\<myproject>\app\tmp\partials was deleted
File c:\<myproject>\app\tmp\partials\ was renamed

Here's a sample of project's files structure (if it helps):
app/
  assets/
  controllers/
  directives/
  app.js
  constants.js
  index.html
gulpfile.js
package.json

Shouldn't I get notified only when that specific app.js file changes?

BTW: I'm using
node v0.12.0
gulp 3.9.0

**Comment by phated** [comment] 2016-02-04 23:14
Duplicate of #651 - please upgrade to gulp 4 for any issues with the file watcher, we've completely switched it to an actively maintained module.

**Closed by phated** 2016-02-04 23:14 UTC

**Comment by matiasbeckerle** [comment] 2016-02-05 11:20
Thank you @phated for clarify that and **sorry** for the noise. We completely missed that one out (#651).
