### ISSUE TITLE
Deprecation warning since Node `14.5.0`

### ISSUE THREAD

**Issue by ehmicky** [gulpjs/gulp#2460] opened 2020-07-01 23:21 UTC
Before you open this issue, please complete the following tasks:

* [x] use the search bar at the top of the page to search this repository for similar issues or discussions that have already been opened.
* [x] if you are looking for help from the gulp team or community, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a problem with the plugin you're using, open a [discussion](https://github.com/gulpjs/gulp/discussions).
* [x] if you think there is a bug in our code, open this issue.

### What were you expecting to happen?

No deprecation warning should be printed on the console since Node `14.5.0`.

### What actually happened?

A deprecation warning is printed on the console since Node `14.5.0`.

```
(node:47881) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
```

### Please give us a sample of your gulpfile

```js
const gulp = require('gulp')

module.exports.example = function () {
  return gulp.src([__filename])
}
```

```sh
$ gulp example
[01:17:58] Using gulpfile ~/Desktop/gulpfile.js
[01:17:58] Starting 'example'...
(node:47881) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
[01:17:58] Finished 'example' after 14 ms
```

### Please provide the following information:
* OS & version: Ubuntu `20.04`
* node version: `v14.5.0`
* npm version: `v6.14.5`
* gulp version: `CLI version: 2.3.0`, `Local version: 4.0.2`

**Comment by laurent22** [comment] 2020-07-04 11:11
I don't know if that can be of any help, but this is the full stacktrace:

> (node:4478) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.
>&nbsp;&nbsp;&nbsp;&nbsp;at emitMakeCallbackDeprecation (domain.js:123:13)
>&nbsp;&nbsp;&nbsp;&nbsp;at FSReqCallback.topLevelDomainCallback (domain.js:134:5)
>&nbsp;&nbsp;&nbsp;&nbsp;at FSReqCallback.callbackTrampoline (internal/async_hooks.js:121:14)

**Comment by fasttime** [comment] 2020-07-06 09:00
I managed to silence the warning by adding this code at the top of my gulpfile.js, before the first `require`.

```js
{
    const { emitWarning } = process;
    process.emitWarning =
    (warning, type, code, ...extraArgs) =>
    code !== 'DEP0097' && emitWarning(warning, type, code, ...extraArgs);
}
```

The root of the problem is that gulp uses the [domain](https://nodejs.org/docs/latest/api/domain.html) module in one of its transitive dependencies ([async-done](https://www.npmjs.com/package/async-done)).

<pre>
└─┬ gulp@4.0.2
  ├─┬ glob-watcher@5.0.3
  │ └── async-done@1.3.2 
  └─┬ undertaker@1.2.1
    └─┬ bach@1.2.0
      ├── async-done@1.3.2  deduped
      └─┬ async-settle@1.0.0
        └── async-done@1.3.2  deduped
</pre>

The domain module has been pending deprecation for years, but no equally usable alternative exists yet, which is a shame. Not sure why Node.js started to emit the warning in version 14.5.0 though. At least I couldn't spot a mention of it in the release notes.

**Comment by noahbrenner** [comment] 2020-07-17 00:12
Looks like warning was the result of https://github.com/nodejs/node/pull/33801, but showing the warning was unintentional and was addressed by https://github.com/nodejs/node/pull/34245 (which *was* merged, despite the GitHub status shown). Hopefully that fix will show up in the next released node version.

**Comment by AlexanderOMara** [comment] 2020-07-23 00:47
The deprecation warning is no longer show in Node 14.6.0.

**Comment by phated** [comment] 2020-07-23 00:58
@AlexanderOMara thanks for the update! And huge thanks to @noahbrenner and everyone else that helped track the upstream problems!

I'm going to close this out now.

**Closed by phated** 2020-07-23 00:58 UTC
