### ISSUE TITLE
Strange gulp.src base behavior

### ISSUE THREAD

**Issue by no-more** [gulpjs/gulp#1580] opened 2016-03-25 11:45 UTC
Hi,

I have a very strange behavior with base option in gulp.src command.
I have 2 projects, running almost same gulp script and config. One is working great, but in the second one I can't make base option works.

This is what I log in the first (working) project:
```
srcFiles:  [ './app/src/**/*.ts', 'node_modules/angular2/typings/browser.d.ts' ]
base:  ./app/src/
dest:  ./build/dist
```
In the dest folder I have files from ./app/src/ without the base (\build\dist), so this is the expected and working behavior.

In the second project, with the same command (slightly different config only) I have : 
```
srcFiles:  [ './app/src/ts/**/*.ts', 'node_modules/angular2/typings/browser.d.ts' ]
base:  ./app/src/ts/
dest:  ./build/dist/app/js/
```
But this time in the dest folder the base option did nothing and I have a directory tree like this : \build\dist\app\js\\**app\src\ts**

Does anybody have a clue, where should I look ?
I'm using the same version of gulp in each project (3.9.1) and all the dev dependencies are the same.

Thanks a lot.

**Comment by phated** [comment] 2016-03-25 15:18
Why are you setting base in the first place? Gulp calculates the base as all directories before the glob, which you are specifying manually.

**Comment by no-more** [comment] 2016-03-25 16:45
I tried without base but had the same result. I thought it would be better to define it because in src I also include browser.d.ts which is not is the same folder.
But you're right in the first project it's working fine without it, but still not in the second project.

**Comment by phated** [comment] 2016-03-28 23:28
@no-more would you say this is a duplicate of #1476 ?

**Comment by phated** [comment] 2016-04-05 02:22
@no-more I just tested the most simple version of this (copy) and it outputs correctly.  See below:

```js
var gulp = require('gulp');

gulp.task('copy', function() {
  return gulp.src(['./app/src/ts/**/*.ts', 'node_modules/angular2/typings/browser.d.ts'], {
    base: './app/src/ts/'
  })
  .pipe(gulp.dest('./build/dist/app/js/'));
});

// Generated Structure
// |-- build
//   |-- dist
//   | |-- app
//   |   |-- js
//   |     |-- somefile.ts
//   |-- node_modules
//     |-- angular2
//       |-- typings
//         |-- browser.d.ts
```

I've got to think this is related to one of your plugins.  I'm going to close this and label it as a plugin problem.  If you can send a repo with a reproduction case or your gulpfile, I could double check this hypothesis.

**Closed by phated** 2016-04-05 02:22 UTC
Labels: further investigation required, help wanted
