### ISSUE TITLE
v5 generating invalid image file in copy job.

### ISSUE THREAD

**Issue by ssojonn** [gulpjs/gulp#2768] opened 2024-03-29 19:38 UTC
### What actually happened?
v5 generating invalid image files. tested with [png, jpg]

### Please give us a sample of your gulpfile

```
gulp.task("public", () => {
  return gulp.src("src/public/**/*").pipe(gulp.dest("copied/"));
});
```

### Terminal output / screenshots
No error on Terminal.

![image](https://github.com/gulpjs/gulp/assets/17677384/f8dad524-e53b-467e-afa5-ed0c039d566a)

### Please provide the following information:
* OS & version :  MacOS Sonoma 14.4.1
* node version (run `node -v`): v21.6.1
* npm version (run `npm -v`): v10.2.4
* gulp version (run `gulp -v`): v5.0.0

**Comment by phated** [comment] 2024-03-29 19:43
Duplicate of https://github.com/gulpjs/gulp/issues/2766

This is not a bug, it is a breaking change. See the linked thread for what you're doing wrong.

**Closed by phated** 2024-03-29 19:44 UTC

**Comment by stefpb** [comment] 2024-09-07 14:51
Thanks! After hours of debugging i found this issue. Would be nice to update the documentation ( https://gulpjs.com/docs/en/getting-started/working-with-files ).
