### ISSUE TITLE
Really hard to figure out what Gulp is from website

### ISSUE THREAD

**Issue by ekallevig** [gulpjs/gulp#913] opened 2015-02-18 17:01 UTC
I heard someone mention Gulp so I go to http://gulpjs.com to find out what it is. The only thing on the page is "Automate and enhance your workflow" (pretty high-level and non-specific) and then some vague features/qualities at the bottom if you scroll down (it mentions Node, so it must be some kind of automation thing for Node).  I click the 'docs' link and it tells me how to install (install what? what is this?). I click the repo homepage and I get another hint -- "streaming build system". Ok still pretty vague but it relates to builds, I guess. Really making me work to figure out what this is!

Maybe take a page from (what I'm assuming is a competing tool) Grunt (http://gruntjs.com/) and just throw a brief description ("The Javascript Task Runner") and a paragraph on the homepage describing what it is: 

"In one word: automation. The less work you have to do when performing repetitive tasks like minification, compilation, unit testing, linting, etc, the easier your job becomes. After you've configured it through a Gruntfile, a task runner can do most of that mundane work for you—and your team—with basically zero effort."

**Comment by heikki** [comment] 2015-02-18 17:05
Duplicate of https://github.com/gulpjs/gulpjs.github.io/issues/25

**Closed by heikki** 2015-02-18 17:05 UTC
