### ISSUE TITLE
Problems with gulp and git rebase

### ISSUE THREAD

**Issue by chillum** [gulpjs/gulp#943] opened 2015-03-07 19:49 UTC
Hi,

I've got a `watch` task that has someting like:
```js
  gulp.watch('src/*.styl', ['css']);
```

That is: if I modify the `.styl` files, I get the `css` task executed.

It works nicely when I edit the files. But when I do `git rebase -i`, gulp goes crazy.

In `git rebase` my source files change several times. And very often I see the situation, when there was only one rebuild during that time. And that is the rebuild of intermediate `.styl` files. That is: `git rebase` saves the file the first time, the second and the third (assuming, I edit my history to squash some commits). I get only one gulp run and the problem is: gulp is run on the first save by git, but does not on second or third.

By this means I get a broken build, that's not up-to-date, when doing `git rebase`. I get a build, that's from the previous version.

I think, that's terribly wrong.

Please tell me, if I'm doing something wrong.

P.S. It's OS X 10.9 here.

**Comment by phated** [comment] 2015-03-14 02:44
Duplicate of https://github.com/gulpjs/gulp/issues/651

**Closed by phated** 2015-03-14 02:44 UTC
