### ISSUE TITLE
gulp4 task system (registration, listing, name uniqueness, registration sequencing)

### ISSUE THREAD

**Issue by jmm** [gulpjs/gulp#972] opened 2015-03-20 14:20 UTC
I'm looking into the issues discussed in #802 and I'd like to clarify some things about how the task system is supposed to work. The examples here aren't necessarily supposed to reflect real world use cases, I'm just trying to understand what's required of the task system implementation and what's fair game to change.

All of the examples are with:
CLI version 0.1.5 (installed from `gulpjs/gulp-cli#4.0`).
Local version 4.0.0-alpha.1 (installed from `gulpjs/gulp#4.0`).

1) The name of each task registered with `gulp.task()` is supposed to be unique per `gulp` invocation, right?

2) Are task names listed with the flags `--tasks|--tasks-simple|--tasks-json`, or in the console logging from `gulp <tasks>`, supposed to uniquely identify functions within the given `gulpfile` (and any other files it may load)?

The last thing discussed in #802 was those listing commands. So let's start with this, what is the expected behavior of `gulp --tasks` here?:

```js
gulp.task('A', function (cb) { console.log("A1"); cb(); });

gulp.task('B', gulp.series(
  'A',
  function A (cb) { console.log("A2"); cb(); }
));
```

I get:

```
+-- A
+-- B
  +-- <series>
    +-- A
    +-- A
```

But of course the "A"s are different functions, so `gulp B` yields

```
Starting 'B'...
Starting 'A'...
A1
Finished 'A' after 1.52 ms
Starting 'A'...
A2
Finished 'A' after 887 µs
Finished 'B' after 6.16 ms
```

3) If `gulp.task()` is called more than once with the same task name, is the later call supposed to overwrite the earlier? Say you have tasks `A` and `B` and `B` depends on `A`, then `A` is overwritten. Is `B` supposed to invoke the original `A` or the new one? For example:

```js
gulp.task('A', function (cb) { console.log("B"); cb(); });
gulp.task('B', gulp.series('A'));
gulp.task('A', function (cb) { console.log("A"); cb(); });
```

Should `gulp B` log `A` or `B`? Should `gulp A` and `gulp B` log different things? (They currently log `A` and `B`, respectively).

**Comment by dinoboff** [comment] 2015-03-21 15:09
Registering a task with a name already used will a overwrite the existing task. That's the expected behaviour.

You might create a [registry](https://github.com/phated/undertaker#custom-registries) to share common tasks between project. You will want to be able to overwrite those common tasks if needed. You can create a registry to warn or forbid overwriting task.

Regarding the unregistered task, function names that are not unique will only affect logging (and `gulp.lastRun`).

**Comment by phated** [comment] 2015-03-22 06:29
`gulp.task` is used for registering methods at the command line and for string lookup from `gulp.series`, `gulp.parallel`, or `gulp.lastRun`.

`gulp.series` and `gulp.parallel` are used for function composition and they return your composed function upon execution, so your example is expected behavior.

@dinoboff opened an issue discussing the `lastRun` use case at https://github.com/phated/undertaker/issues/19

@jmm or @dinoboff do you think there is a good way to outline this expected behavior in the docs?

**Comment by dinoboff** [comment] 2015-03-22 22:40
- `gulp.task` should mention that if a task with the same name already exist it will overwrite.
- there should be a note added to `gulp.series` and `gulp.parallel` a warning about the confusing log message when using the same name for task and function.

**Comment by phated** [comment] 2015-04-15 07:03
We've fixed the `lastRun` bug in undertaker by using a WeakMap to determine the function to run, so you will only up with the last time of the actual function, not things that collide on name.

We just need to agree on a good way to document the behavior of gulp.task/series/parallel

**Comment by jmm** [comment] 2015-04-15 12:57
@dinoboff
> Registering a task with a name already used will a overwrite the existing task. That's the expected behaviour.

Ok, thanks.

@phated 

> We just need to agree on a good way to document the behavior of gulp.task/series/parallel

What do people use the task listing functions for? I think you need to say something like:

***
Task names are only as unique as you make them. If you pass a function to `gulp.series()` or `gulp.parallel()` that has the same name as another function passed to those methods elsewhere or a registered task, then the same name will appear in task dependency lists referring to different functions. Example:

```js
gulp.task('C', function () {});
gulp.task('A', gulp.series(function C () {}));
gulp.task('B', gulp.series('C'));
```

Both `A` and `B` will list `C` as a dependency, but in each case `C` refers to a different function.

Similarly, if you depend on a registered task and later overwrite the registered name with a new function, the registered name will refer to different functions at different times. Example:

```js
gulp.task('C', function () {});
gulp.task('A', gulp.series('C'));
gulp.task('C', function () {});
gulp.task('B', gulp.series('C'));
```

In a task list, the top level `C` and the `C` that `A` depends on will refer to the same function, while the `C` that `B` depends on refers to a different function.
***

Can I get a reply at https://github.com/gulpjs/gulp/issues/969#issuecomment-84975436 ?

**Comment by jmm** [comment] 2015-04-15 13:36
@phated How much will is there to address the sequencing issues discussed in #802? I'm willing to look into it, and I have some ideas to pursue, but I don't want to sink time into it only to have it shot down (assuming I can make it work) only because no one cares, or is actually opposed to it to begin with.

**Comment by phated** [comment] 2015-04-21 21:21
@jmm sorry for the delayed response.  I am open to someone working on the issue outlined in #802 because the current implementation makes it pretty difficult to split a gulpfile up.  If you could get this working, we wouldn't need to make the suggestions proposed in #1028

**Comment by phated** [comment] 2015-04-21 21:22
@jmm Also, I think we have enough tests in undertaker to attempt this without changing any of them and retaining current feature parity.

**Comment by jmm** [comment] 2015-04-22 18:14
@phated no problem. Ok, I'm looking into this. 

So, users are being encouraged to only `gulp.task()` to expose tasks to the CLI. But is the goal here to just make "forward referencing" work for registered tasks? And users are on their own when it comes to splitting up files and sharing private functions?

> Also, I think we have enough tests in undertaker to attempt this without changing any of them and retaining current feature parity.

So you're saying just make the current tests pass and avoid altering or adding to them?

**Comment by phated** [comment] 2015-04-22 18:37
@jmm if forward referencing can be made to work, it will only be made to work with things you register with `gulp.task` because we wouldn't have control over plain functions (not registered with `gulp.task`).

I think tests should be added for forward referencing, but I want all the current tests to pass because that is the currently defined behavior that people are using when testing gulp 4.

**Comment by jmm** [comment] 2015-04-22 19:16
@phated 

> if forward referencing can be made to work, it will only be made to work with things you register with `gulp.task` because we wouldn't have control over plain functions (not registered with `gulp.task`).

So the thing with that is I think it's going to lead people to register functions that they don't want exposed to the CLI with `gulp.task()` just to be able to do the forward referencing in a way that allows things like globbing in a directory of gulpfiles. I'm starting to wonder if something like `gulp.private()` makes sense (working like `gulp.task()` except it only setting / getting functions in the registry and not exposing to the CLI, to allow sharing between files using the same registry without having to manually manage load order or dependencies between files).

> I think tests should be added for forward referencing, but I want all the current tests to pass because that is the currently defined behavior that people are using when testing gulp 4.

Ok.

**Comment by jmm** [comment] 2015-04-23 21:21
@phated Please see  #1038.

**Comment by jkarttunen** [comment] 2015-04-30 22:25
One annoying thing (that teaches a bit too much javascript) is that now function names collide easily with plugin names.

var mocha = require('gulp-mocha');
function mocha() {
    console.log('mocha')
}
gulp.task(mocha);
==> AssertionError: Task name must be specified

Maybe at least better error message for a case where the named item is not a function / task?

**Comment by contra** [comment] 2015-04-30 22:37
@jkarttunen Or name your tasks based on what its doing and not what plugin you're using which is a better practice

**Comment by jkarttunen** [comment] 2015-05-01 19:37
@contra My point exactly. A lot of people will be encountering this after naming tasks badly, and when adding a watch task that needs a function name. Or when migrating from gulp 3 to gulp 4. 

Lot of examples (https://github.com/gulpjs/gulp/blob/4.0/docs/recipes/mocha-test-runner-with-gulp.md#running-mocha-tests-when-files-change) and seed projects seem to use this task naming, so maybe the best naming practice in gulp 4 needs to be communicated clearly.

**Comment by phated** [comment] 2015-05-01 19:41
@jkarttunen this isn't something to be fixed but should be noted on the migration guide

**Comment by jkarttunen** [comment] 2015-05-02 11:25
@phated Agree.

**Comment by mikestopcontinues** [comment] 2015-05-05 13:36
I'd like to offer my workflow to this discussion, as I'm having a hard time switching to gulp 4 on account of task registration.

At my current gig, I'm in charge of a half-dozen projects with nearly identical, somewhat complex gulp task chains. I keep the default task registration in a separate repo. Individual projects import the common tasks, and then override any particular tasks that vary. For example, one css chain also builds and concatenates a font icon stylesheet, another watches a few additional directories for changes.

This works because gulp 3 uses the last registered task with that name, and it makes my life easy. What benefit is there to doing task lookup for .parallel and .series up front?

**Comment by jmm** [comment] 2015-05-05 14:07
> What benefit is there to doing task lookup for .parallel and .series up front?

In other words, in my example # 3, why should `$ gulp B` log `B` instead of `A`?

**Comment by mikestopcontinues** [comment] 2015-05-05 16:18
@jmm, precisely. I think logging `A` offers more flexibility.

**Comment by phated** [comment] 2015-07-26 01:14
Figured I would update this post.  It was easiest to implement forward references as a custom registry - see https://github.com/undertakerjs/undertaker-forward-reference

**Comment by mikestopcontinues** [comment] 2015-07-26 13:28
Hey, thanks man! I'm happy to have official support! :)

**Comment by phated** [comment] 2015-08-21 23:35
@jmm has this been sufficiently dealt with?  I'd like to close if so

**Comment by jmm** [comment] 2015-08-26 13:38
@phated I haven't tried it, but I took a quick look at the implementation and it seems like it'll do it. I should note that this means the task listing commands will sort of lie sometimes, right? (Could've been the case with my PR too -- don't remember.) E.g. if you do:

```js
gulp.task(
  'A',
  // Never defined
  gulp.series('B')
);
```

```sh
$ gulp --tasks
```

You'll get something like:

```
+-- A
  +-- <series>
    +-- B
```

But it'll fail at runtime, right?

**Comment by phated** [comment] 2015-08-26 18:19
@jmm correct, but since you have to explicitly use a custom registry for forward references, you will know that is the case.  I actually prefer that it shows the tasks that will be defined in the future.  Also, I added the error message `'Forward referenced task \'' + name + '\' not defined before use'` if it still doesn't exist at runtime.  I'm going to close this for now.

**Closed by phated** 2015-08-26 18:19 UTC
Labels: documentation, gulp4, help wanted
