### ISSUE TITLE
need to upgrade version of graceful-fs

### ISSUE THREAD

**Issue by GeoffreyPlitt** [gulpjs/gulp#1570] opened 2016-03-17 22:40 UTC
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible

**Comment by phated** [comment] 2016-03-17 23:12
Duplicate of https://github.com/gulpjs/gulp/issues/1568 - stop opening these

**Closed by phated** 2016-03-17 23:12 UTC
