### ISSUE TITLE
Should gulp.task('foo', gulp.task('bar')) work?

### ISSUE THREAD

**Issue by ibc** [gulpjs/gulp#1222] opened 2015-08-31 11:03 UTC
```js
gulp.task('foo', gulp.task('bar'));
```

It just produces a ugly tasks tree (`gulp -T`).

Using `series` produces a correct tree.

```js
gulp.task('foo', gulp.series('bar'));
```

**Comment by contra** [comment] 2015-08-31 22:49
I think this is a duplicate of #1159

**Closed by contra** 2015-08-31 22:49 UTC
