### ISSUE TITLE
Gulp v5.0.0 does not work if the root folder contains too many files (Works in Gulp v4.0.2)

### ISSUE THREAD

**Issue by zivkovic** [gulpjs/gulp#2785] opened 2024-04-07 13:16 UTC
### What were you expecting to happen?
The script to work with Gulp v5.0.0

### What actually happened?
Gulp v5.0.0 starts up, then throws error `RangeError: Maximum call stack size exceeded`.

### Please give us a sample of your gulpfile
```js
const { src, dest, parallel, series, watch } = require("gulp");
function streamTask() {
  return src(["pdf/**"]);
}
exports.default = streamTask;
```

### Terminal output / screenshots
Gulp v5.0.0:
![image](https://github.com/gulpjs/gulp/assets/2651524/af4ed00b-c5db-42c7-9b58-780a47580eca)

Gulp v4.0.2:
![image](https://github.com/gulpjs/gulp/assets/2651524/442e452a-45ce-45b5-8e29-4e6ac76fddb5)

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: Linux Manjaro 23.1.4
* node version (run `node -v`): v21.7.2
* npm version (run `npm -v`): 10.5.0

### Additional information
I created a sample project with the above gulpfile and the following `package.json`:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "dev": "gulp"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^5.0.0"
  }
}

```

In the root folder I have the following structure:
```
test/pdf/*  // Contains 50 pdf files
test/media/* // Contains approx 84000 random files (images, pdf, videos, etc...)
test/package.json
test/gulpfile.js
```

Command used to get file count in root folder: `find . -type f | wc -l`, result: `84039`

If I simply change the gulp version from `"gulp": "^5.0.0"` to `"gulp": "^4.0.2"` the project works as intended.

**Comment by phated** [comment] 2024-04-07 23:11
This is a duplicate of https://github.com/gulpjs/glob-stream/issues/125, please follow that issue for updates.

**Closed by phated** 2024-04-07 23:11 UTC
