### ISSUE TITLE
gulp4 documentation questions

### ISSUE THREAD

**Issue by erikkemperman** [gulpjs/gulp#1319] opened 2015-10-09 11:40 UTC
Hi there! I've just started playing around with the 4.0 branch... And noticed a couple of little issues with the documentation.

The description of the `registry` function inherited from Undertaker, in [API.md](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#registry), says its argument can be "A registry instance or constructor". However, it actually only allow instances. If I pass in a constructor it complains that "AssertionError: Custom registries must be instantiated, but it looks like you passed a constructor".

Just below that bit, [here](https://github.com/gulpjs/gulp/blob/4.0/docs/API.md#example), is an example of how we might use this `registry` function to implement re-usable tasks. This is a really great addition to gulp!

(Of course, this was possible in older versions, but felt a bit kludgy to me -- maybe I was just doing it wrong; I used to just write a common module around a bunch of functions that would return a function I could pass into `gulp.task`).

Anyway, I noticed that the example given is subtly different from the examples in the Undertaker documentation, [here](https://github.com/phated/undertaker#sharing-tasks). Specifically the gulp example suggests we call `this.set` from within the custom registry's constructor, while the Undertaker documentation suggests we extend the `init` function and then call `task` on the (taker/gulp) instance passed as an argument to that `init` function.

I haven't been able to come up with any significant benefits or disadvantages to either approach thus far; both seem to do the job just fine. Or am I missing something here?

Either way, I figured that it might be good to align these docs one way or the other, especially since one links to the other.

In general, thanks for making this available, much appreciated. Looking forward to 4.0 release!

**Comment by phated** [comment] 2015-10-09 17:51
The gulp docs were updated by a community member before a bunch of changes to undertaker.  Please follow the undertaker docs.  Going to close this as a duplicate of #1281

**Closed by phated** 2015-10-09 17:51 UTC

**Comment by erikkemperman** [comment] 2015-10-09 18:12
Sounds about right, thanks for taking the time.

Since above I actually ran into an interesting difference between calling `gulp.task` from within `init` on the registry's prototype and calling `this.set` from within the registry's constructor. In both cases my task runs fine, but in the second case `gulp -T` throws an exception.

Haven't had time to dive in any deeper -- and probably I won't, if the way forward is to do it undertaker's way, which works as expected. In stead I might submit a PR for this part of API.md to align with undertaker's example. Unless... You expect that to change much in the near future?

**Comment by phated** [comment] 2015-10-09 18:19
@erikkemperman Undertaker has pretty much stabilized, a PR would be much appreciated.

**Comment by erikkemperman** [comment] 2015-10-12 14:59
So... For anyone stumbling into this thread somehow: the upshot of above is that with latest Undertaker you'll get in trouble if you call the methods prescribed by `undertaker-registry` yourself. Leave that to Undertaker/Gulp.

Specifically, in the above instance, it turns out the metadata got out of whack, which manifested not in running the task from CLI (which worked) but in listing the task tree (which didn't).

Maybe Undertaker/Gulp documentation should mention this risk explicitly somewhere, especially since the Gulp docs up until now included an example of how not to do it?

As promised I will submit a PR for the Gulp#4.0 docs. But looking into this made me wonder about the way that metadata is handled by Undertaker more generally. Since said PR would aim to align Gulp's docs with Undertaker's, I'll probably first see if that goes anywhere.

@phated So I might be firing some issues/PRs into Undertaker repo, hope you don't mind the hassle too much.
