### ISSUE TITLE
Respect the explicitly set --cwd when --gulpfile argument is also set

### ISSUE THREAD

**Issue by prodelay** [gulpjs/gulp#867] opened 2015-01-13 13:50 UTC
When someone tries to run __Gulp__ with both `--cwd` and `--gulpfile` parameters set, __Gulp__ fails with _"Local gulp not found in..."_ error [because of](https://github.com/gulpjs/gulp-cli/blob/master/index.js#L88) undefined `env.modulePath`.

That is because __Liftoff__ [tries to resolve](https://github.com/tkellen/node-liftoff/blob/master/index.js#L89) `modulePath` with preference to `configBase` directory over `cwd`.

It was said ([by __tkellen__ here](https://github.com/tkellen/node-liftoff/issues/10#issuecomment-41284129)) that __Gulp__ should _"respect its `cwd` choice and `chdir` to it"_.

Could it possibly be implemented?

**Comment by heikki** [comment] 2015-01-13 14:41
@prodelay That seems to be working for me with gulp 3.8.10.

Do you have local modules installed next to gulpfile?

**Comment by prodelay** [comment] 2015-01-14 04:19
Hi, @heikki!
No, node_modules are in `cwd`. That is the case.

I believe that one of the use cases for simultaneous use of `--cwd` and `--gulpfile` is when someone has the environment with local modules in `cwd`, but needs to use external `gulpfile`.

**Comment by heikki** [comment] 2015-01-14 11:10
That's quite odd. What's the reason for putting modules and gulpfile to different places?.  Saving disk space?

I use the combination when gulp (with required modules) is installed in one place and I need tasks operate on some other place.

**Comment by phated** [comment] 2015-01-18 22:42
What's the goal here?  Something named `my-other-gulpfile.js` inside the directory specified by `--cwd`?  I tried this recently and it didn't work.

**Comment by prodelay** [comment] 2015-02-04 11:23
The goal is to point `gulp` to the directory with `node_modules` while have the `gulpfile.js` and all the sources in another one.

**Comment by heikki** [comment] 2015-02-14 14:52
I think this works as it is supposed to. Requires in gulpfile are relative to gulpfile and no command line option changes that. I fail to see how anything else would be useful.

@phated :+1: / :-1: ?

**Comment by daniele-orlando** [comment] 2015-02-14 20:44
Same here.
``` shell
root/
    node_modules/
    support/
        gulpfile.js
```

``` shell
cd root
gulp --gulpfile support/gulpfile.js
```
throws **"Local gulp not found in..."**.

**Comment by heikki** [comment] 2015-02-14 20:56
@daniele-orlando Do you have latest gulp installed?

```
∴ baz npm list
/Users/heikki/Desktop/baz
└── gulp@3.8.11

∴ baz ls -la
total 0
drwxr-xr-x  4 heikki  staff  136 Feb 14 16:50 .
drwx------+ 9 heikki  staff  306 Feb 14 15:48 ..
drwxr-xr-x  4 heikki  staff  136 Feb 14 15:48 node_modules
drwxr-xr-x  3 heikki  staff  102 Feb 14 16:51 support
∴ baz gulp --gulpfile support/gulpfile.js 
[16:55:05] Working directory changed to ~/Desktop/baz/support
[16:55:05] Using gulpfile ~/Desktop/baz/support/gulpfile.js
[16:55:05] Starting 'default'...
[16:55:05] Finished 'default' after 83 μs
```

**Comment by heikki** [comment] 2015-02-15 22:02
My interpretation of the current behaviour is that if you specify only `--cwd` then gulpfile is expected to be there too. Adding `--gulpfile` will override that expected gulpfile location.

Relevant [docs](https://github.com/gulpjs/gulp/blob/master/docs/CLI.md#flags):

> --gulpfile <gulpfile path> will manually set path of gulpfile. Useful if you have multiple gulpfiles. This will set the CWD to the gulpfile directory as well
> --cwd <dir path> will manually set the CWD. The search for the gulpfile, as well as the relativity of all requires will be from here

I think the title of the question is wrong since the problem is actually about separating gulpfile and node_modules to entirely different places and none of the cli options claim to make that possible.

@prodelay Does that make sense?

**Comment by tkellen** [comment] 2015-02-15 23:58
@prodelay can you do a PR on this repo to add the command you're trying to do that is failing?
https://github.com/tkellen/liftoff-test

**Comment by prodelay** [comment] 2015-02-16 11:30
@heikki, yeah, you are exactly right.
The reason to open that question was that (according to that docs) either `--cwd` or `--gulpfile` option is ignored.

I believe that someone may want to take logic from `gulpfile.js` in __one__ folder, process it over the __other__ folder, while store all of his `node_modules` in the __third__ folder.
I am [not alone](http://stackoverflow.com/questions/24398878/custom-gulpfile-path-that-is-not-an-ancestor-directory) here. :smirk:

Of course, there are workarounds like, e.g. `process.chdir()`.
I, personally, simlinked `node_modules` to `/` so `node` can find them no matter what (according to [nodejs.org/api/modules](http://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders)).

@tkellen as to `liftoff-test` structure desired command may be like:

    hacker --hackerfile sibling/hackerfile.js --cwd main/

**Comment by daniele-orlando** [comment] 2015-02-17 17:48
@heikki Yes, 3.8.11

With your project structure even in my case Gulp works fine.
But the situation described by me is different and gulp behaves weird.

I explain:
``` shell
root/
    node_modules/
    support/
        gulpfile.js

$ cd root
$ gulp --gulpfile support/gulpfile.js
# Runs fine!
```

``` shell
root/
    sandbox/
        node_modules/
    support/
        gulpfile.js

$ cd root/sandbox
$ gulp --gulpfile ../support/gulpfile.js
# Local gulp not found in root/support
```

The problem is in the `..` path. —.—

**Comment by heikki** [comment] 2015-02-17 17:58
Well.. the project structure was yours, not mine :smile: 
Your second version is basically the same that @prodelay talks about. 

https://github.com/gulpjs/gulp/issues/867#issuecomment-74439692

> I think the title of the question is wrong since the problem is actually about separating gulpfile and node_modules to entirely different places and none of the cli options claim to make that possible.

**Comment by tkellen** [comment] 2015-02-17 17:58
Gulp doesn't behave strangely, this is how node works:
http://nodejs.org/api/modules.html#modules_all_together

**Comment by phated** [comment] 2015-03-22 06:31
poking this thread - @contra @heikki @tkellen where do we stand on this? does it need changing in any way or can we close as expected behavior?

**Comment by contra** [comment] 2015-03-23 05:58
I think we can close it

**Closed by contra** 2015-03-23 05:58 UTC
