### ISSUE TITLE
Watch doesn't handle "added" events for paths starting from ./

### ISSUE THREAD

**Issue by zuzusik** [gulpjs/gulp#1257] opened 2015-09-15 16:27 UTC
Gulp 3.9.0.

gulpfile.js:
```javascript
var gulp = require('gulp');

gulp.task('watch', function() {
  gulp.watch('./test/*.*', function() {
    console.log('Directory content changed');
  });
});
```
With this config only changes on existing files in `test` folder trigger task execution. Creating files has no effect.

Removing `./` from path fixes the issue.

**Comment by phated** [comment] 2015-09-15 18:51
Duplicate of #651 - Opening more issues about the file watcher isn't helpful, as it isn't changing in gulp 3.9 and going to be switched to chokidar in gulp 4

**Closed by phated** 2015-09-15 18:51 UTC
