### ISSUE TITLE
Unexpected result when I use gulp.src()

### ISSUE THREAD

**Issue by zhangzhiqiang37** [gulpjs/gulp#2501] opened 2020-10-16 04:03 UTC
### What were you expecting to happen?
Hi, I have a problem with gulp.src when I use a relative path.
e.g.
```js
gulp.src(['../src/pages/**/*.js', '!../src/pages/index/index.js'])
```
I want to exclude the `../src/pages/index/index.js`

### What actually happened?
Actually, I get all file, include `../src/pages/index/index.js`
And I debug the code, the final pattern you use(`path.join`) is `/User/xxx/project/build/../src/pages/**/*.js` and `/User/xxx/project/build/../src/pages/index/index.js`

Ps: process.cwd() is `/User/xxx/project/build/`

### Please give us a sample of your gulpfile

```js
gulp.src(['../src/pages/**/*.js', '!../src/pages/index/index.js'])
```

### Please provide the following information:
* OS & version : MacOS Catalina 10.15.7
* node version : 8.11.3
* npm version : 5.6.0
* gulp version : 4.0.2

**Comment by phated** [comment] 2020-10-16 04:15
Please provide a duplication repository that shows the problem in a GitHub Action.

**Comment by zhangzhiqiang37** [comment] 2020-10-19 08:05
> Please provide a duplication repository that shows the problem in a GitHub Action.

https://github.com/zhangzhiqiang37/gulp-src-test/runs/1273921501?check_suite_focus=true

**Comment by zhangzhiqiang37** [comment] 2020-10-19 08:06
> Please provide a duplication repository that shows the problem in a GitHub Action.

https://github.com/zhangzhiqiang37/gulp-src-test/runs/1273921501?check_suite_focus=true

@phated

**Comment by phated** [comment] 2020-10-21 20:40
@zhangzhiqiang37 Thanks! This is actually a duplicate of #2211 and https://github.com/gulpjs/vinyl-fs/issues/306 - you can use the `cwd` option as a workaround.

**Closed by phated** 2020-10-21 20:40 UTC
