### ISSUE TITLE
Error watching folder for changes: EPERM

### ISSUE THREAD

**Issue by ScorpioCoding** [gulpjs/gulp#1921] opened 2017-03-04 13:11 UTC
**What were you expecting to happen?**
I was expecting to get an event trigger : deleted

**What do you whish to achieve**
IS when the user manualy deletes a file or folder or both within the **src** folder.
That it is automatically also done in the **dist** folder.
With a minimal condition that they match naming

**What actually happened?**
```
Error: Error watching file for changes: EPERM
at exports._errnoException (util.js:1029:11)
at FSEvent.FSWatcher._handle.onchange (fs.js:1375:11)
```
**Npm dependencies**
`gup and browser-sync`
_Aha you might say there's your problem it's the other dependency.
You could be right, but to test my issue gulp has to be running continuously  and thus browser-sync.
And that's when we see the issue_

**Sample code**
```
var gulp = require('gulp');
var browserSync   = require('browser-sync');

gulp.task('browserSync', function () {
  browserSync({
    server: {
      baseDir: './dist',
    },
  });
});

gulp.task('html', function () {
  return gulp.src('./dist/**/*.html')
    .pipe(browserSync.reload({ stream: true }));
});

gulp.task('watch', function () {
  gulp.watch('dist/**/*.html', ['html']);
  gulp.watch('src/pug/**/*.pug', ['pug']);

  console.log('here');
  var watcher = gulp.watch('src/**/*');
  watcher.on('change', function(event){
    console.log('trigger fired : ' + event.type);
    if (event.type === 'deleted') {
      console.log('delete trigger fired');
    }
  });
});

gulp.task('default', ['watch', 'browserSync']);

```

**Testing**
```
Files - add,paste,delete,move, - work fine
Folders - add,paste - work fine
Folders - move, delete - ERROR
```
**What version of browser-sync are you using?**
`browser-sync -v 2.18.8`
**What version of gulp are you using?**
```
CLI version 3.9.1
Local version 3.9.1
Local version 3.8.11
```

**What versions of npm and node are you using?**
```
node v7.7.1
npm 4.1.2
```

**What OS are you using?**
```
Microsoft Windows 10 Pro x64
Version	10.0.14393 Build 14393
```

**Testing in different Editors and using windows explore**
```
.Atom -v1.14.4 x64
.VScode -v1.10.1
```
**Testing- Directory Structure**
![filestructure](https://cloud.githubusercontent.com/assets/20724826/23582287/944b350c-0127-11e7-8a08-ab07440159c1.PNG)

**Comment by phated** [comment] 2017-03-06 20:14
The gulp 3.x watcher has problems.  You can use the `gulp-watch` module or `chokidar` as a holdover until gulp 4.

Duplicate of #651

**Closed by phated** 2017-03-06 20:14 UTC

**Comment by szachara** [comment] 2017-03-18 10:45
Hi, I have the same problem, but for me this happens, when `gulp watch` is running and I switch to another branch with git.

What is the solution?
We are using laravel elixir and I don't have any control what is used in gulpfile.js and how are our assets compiled, think this will be the problem :/

**Comment by BrightShadow** [comment] 2017-11-22 11:14
The answer: 

> The gulp 3.x watcher has problems.

is not sufficient here. What if I have many, many tasks already written using gulp watch and it is not working. the 3.x version should be supported as same as the newest version.

**Comment by BrightShadow** [comment] 2017-11-22 11:16
By the way, running console/bash as administrator solved my issue under **Windows 10.**
