### ISSUE TITLE
depricated lodash@1.0.2 in gulp/vinyl-fs/glob-watcher/gaze/globule/

### ISSUE THREAD

**Issue by AlhasanIQ** [gulpjs/gulp#1497] opened 2016-01-23 05:54 UTC
As in the title .
a deprecated version of `lodash` in 
`gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/node_modules/lodash/`

**Comment by TrySound** [comment] 2016-01-23 06:11
@AlhasanIQ We all know about it. Don't create duplicated issues.
https://github.com/gulpjs/gulp/issues/1485

**Comment by phated** [comment] 2016-01-23 07:22
Duplicate of #1485 - please look at the issue list before posting.

**Closed by phated** 2016-01-23 07:22 UTC
