### ISSUE TITLE
Gulp 4 Alpha 3 not handling src correctly

### ISSUE THREAD

**Issue by Dan503** [gulpjs/gulp#2093] opened 2018-01-09 23:30 UTC
**What were you expecting to happen?**

I have this basic copy task:

```````js
  gulp.task('copy:scripts', () => {
    return gulp.src([
      'src/_scripts/**/*',
      '!src/_scripts/{**/\_*,**/\_*/**}',
    ])
    .pipe(gulp.dest('app/scripts'));
  })
```````

What should happen is that it looks in the `src/_scripts` folder and copies everything inside it into the `app/scripts` folder. It should ignore any file that either starts with an underscore, or is held in a folder that starts with an underscore.

**What actually happened?**

It doesn't seem to understand the `!src/_scripts/{**/\_*,**/\_*/**}` syntax any more. I had to break it out into seperate "not" strings. It also didn't handle the "base" setting automatically like it is supposed to. It ended up saving the files into `app/scripts/src/_scripts` instead of `app/scripts/`. To fix the issues This is what I ended up with.

```````js
  gulp.task('copy:scripts', () => {
    return gulp.src([
      'src/_scripts/**/*',
      '!src/_scripts/**/\_*',
      '!src/_scripts/**/\_*/**',
    ], { base: 'src/_scripts' })
    .pipe(gulp.dest('app/scripts'));
  })
```````

**What version of gulp are you using?**

Gulp 4.0.0 aka 4-alpha.3

**What versions of npm and node are you using?**
npm: 5.5.1
Node: 6.12.0

(I know my node is out of date, I have a project that requires Node 6 to work)

**Comment by phated** [comment] 2018-01-09 23:34
@jonschlinkert @doowb  can you guys help out here?

**Comment by doowb** [comment] 2018-01-09 23:58
I'll take a look in a little bit.

**Comment by doowb** [comment] 2018-01-10 03:39
@Dan503 I'm not able to reproduce the issue that you're having. I used `nvm` to switch to node 6.12.0 to make sure it wasn't a node version.

I also installed gulp and gulp-cli with the following commands:

```bash
npm i -g gulp-cli
npm i gulp@next
```

**Comment by doowb** [comment] 2018-01-10 03:55
I created a repo with some mock files to show what I'm seeing: https://github.com/doowb/gulp-issue-2093.git

@Dan503 let me know if the folder structure looks like what you're expecting.

**Comment by Dan503** [comment] 2018-01-10 04:29
I'm not able to take a look right now, can you check gulp.watch is working in the mean time?
https://github.com/gulpjs/gulp/issues/2094

**Comment by Dan503** [comment] 2018-01-10 05:17
In the reduced test case that you created, it looks like it's all working as expected. It must be an issue with my set up.

Thanks for creating the test environment. I'll close the watch issue as well. It seems like that is working on your test environment as well.

**Comment by Dan503** [comment] 2018-01-10 06:30
I created a pull request in your mini gulp set up that is able to successfully replicate the issue
https://github.com/doowb/gulp-issue-2093/pull/1

**Comment by doowb** [comment] 2018-01-10 13:32
@Dan503 as @jonschlinkert points out [in this comment](https://github.com/doowb/gulp-issue-2093/pull/1#discussion_r160622146) you shouldn't be using `path` methods on the glob patterns. Instead, pass the patterns like you do in the original example and use the `cwd` option when specifying the working directory is necessary.

I'm going to close this since it isn't a bug.

**Closed by doowb** 2018-01-10 13:32 UTC
