### ISSUE TITLE
Release 4.0.0-alpha.1 + a new 4.0.0-alpha.2 on NPM

### ISSUE THREAD

**Issue by mgcrea** [gulpjs/gulp#1337] opened 2015-10-20 16:46 UTC
Would you consider publishing a couple of releases on NPM? Currently we're linking our projects against the `#4.0` branch, but it would be great to start using proper NPM releases.

**Comment by callumacrae** [comment] 2015-10-20 16:53
Duplicate of https://github.com/gulpjs/gulp/issues/865

I'm for this: the only reason I can't use Gulp 4.0 at work is because they don't like me using versions from github. I have no idea what mirroring npm 3 means though

**Comment by Romanx** [comment] 2015-10-20 17:25
I wouldn't be against this, we're targeting 4.0 at work which has caused inconsistencies in our CI builds (which to be honest we expected when targeting a branch)

**Comment by phated** [comment] 2015-10-20 18:17
No. I've discussed this at length in other issues. Please stop opening new ones. I've also recently chatted with a friend at npm who **again** confirmed that publishing prerelease versions is a bad idea.

**Closed by phated** 2015-10-20 18:17 UTC

**Comment by mgcrea** [comment] 2015-10-20 18:19
Ok, I'll fork and release then.

**Comment by phated** [comment] 2015-10-20 18:24
@mgcrea instead of all of that how about you put your effort into fixing one of the couple of problems left before a real release :disappointed:
