### ISSUE TITLE
Gulp cannot find specified files, when the path contains square brackets ( '[' and ']' )

### ISSUE THREAD

**Issue by richrdkng** [gulpjs/gulp#1027] opened 2015-04-19 09:18 UTC
By convention, throughout projects i have worked with, the main project folder is called "Project [the actual project name]",
e.g.: **Project [gulp-is-awesome.js]**

The problem with this naming convention is that gulp will not find the specified files.
i.e.: when using gulp:
```javascript
gulp.task('default', function() {
    return gulp
        .src('test/**/*.*')
        .pipe(debug());        
});
```
...gulp won't find anything within the specified glob, even when it contains files.
The result will be:
```
gulp-debug: 0 items
```
...instead of the actual files.

Of course, renaming the folder by simply just omit the square brackets (**Project gulp-is-awesome.js**) will fix this issue.
__But the actual problem will still remain, that is gulp cannot find/use files from folders their names contain square brackets.__

This issue occurred on Windows 7, Windows 8 and Windows 8.1.
__Did not test on other platforms yet.__
```json
"iojs": "1.7.1"
"gulp": "^3.8.11",
"gulp-debug": "^2.0.1"
```

**Comment by tunnckoCore** [comment] 2015-04-19 11:58
you want to select only the folders like this or files from them?

**Comment by tunnckoCore** [comment] 2015-04-19 11:59
i'm sure this is glob misunderstanding + minimatch fails

**Comment by tunnckoCore** [comment] 2015-04-19 12:01
say you have
```
Project [gulp-is-awesome.js]
Project [my-awesome-project.js]
```
this will work
```js
var gulp = require('gulp')
var debug = require('gulp-debug')

gulp.task('default', function() {
    return gulp
        .src('./**/Project*\\[*.*\\]')
        .pipe(debug());
});
```

**Comment by richrdkng** [comment] 2015-04-19 15:49
I would like to select .js files.
For example: __*.js files__ from the __folder "test"__ within the project.

I have tried your approach. It can list other projects too, but the problem is, that it cannot see files in the current project. (e.g.: **Project [project.js]/test/test.js**).

Also it is really slow, 6+ seconds.

Thanks for the quick reply.

**Comment by tunnckoCore** [comment] 2015-04-19 16:24
yea, the more plugins in pipe gulp become more slow and slow, this is because the through (i.e. transform stream)

try `'./**/Project*\\[*.*\\]/test/*.js` if you want only js files in test dir 
or `'./**/Project*\\[*.*\\]/test/**/*.js` if you want all js files in all sub dirs of test dir

**Comment by tunnckoCore** [comment] 2015-04-19 16:26
actually the real problem of gulp and vinyl-fs/glob-stream based apps is glob + minimatch combo

**Comment by tunnckoCore** [comment] 2015-04-19 16:30
if glob-stream is
```
glob-stream x 584 ops/sec ±5.09% (66 runs sampled)
```
my implementation is
```
glob-fs x 58,947 ops/sec ±5.21% (74 runs sampled)
```

**Comment by phated** [comment] 2015-04-19 18:18
Duplicate of https://github.com/gulpjs/gulp/issues/616

**Closed by phated** 2015-04-19 18:18 UTC
