### ISSUE TITLE
gulp-v4 earliest task-execution

### ISSUE THREAD

**Issue by SalathielGenese** [gulpjs/gulp#1667] opened 2016-05-18 15:38 UTC
Gulp 4 is executing tasks the earliest...
Thus, it becomes difficult to create some dependencies... as one may got.
```code
assert.js:90
  throw new assert.AssertionError({
  ^
AssertionError: Task never defined: clean-js
    at getFunction (/home/salathielgenese/Documents/open.icon/node_modules/undertaker/lib/helpers/normalizeArgs.js:15:5)
    at arrayMap (/home/salathielgenese/Documents/open.icon/node_modules/lodash.map/index.js:34:21)
    at map (/home/salathielgenese/Documents/open.icon/node_modules/lodash.map/index.js:138:10)
    at normalizeArgs (/home/salathielgenese/Documents/open.icon/node_modules/undertaker/lib/helpers/normalizeArgs.js:19:10)
    at Gulp.series (/home/salathielgenese/Documents/open.icon/node_modules/undertaker/lib/series.js:13:14)
    at /home/salathielgenese/Documents/open.icon/gulpfile.js:6:32
    at Object.<anonymous> (/home/salathielgenese/Documents/open.icon/gulpfile.js:24:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```
when running
```shell
gulp build-js
```
My first tought was that gulp was not functioning at all, so I commented some code...
```javascript
+function(del, gulp, merge2, sass, rename, uglify, uglifycss, typescript, sourcemaps)
{
    'use strict';
    // const project = typescript.createProject("tsconfig.json");

    gulp.task('build-js', gulp.series('clean-js', 'compile-js', 'minify-js'))
    // gulp.task('watch-js', () => gulp.watch(['web/ts/*.ts', 'web/ts/**/*.ts'], gulp.series('build-js')))
    gulp.task('clean-js', () => del(['web/js/*.js', 'web/js/**/*.js', 'web/js/*.map', 'web/js/**/*.map', 'web/js/*.d.ts', 'web/js/**/*.d.ts']))
    // gulp.task('minify-js', () => gulp.src(['web/js/*.js', 'web/js/**/*.js', '!web/js/*.min.js', '!web/js/**/*.min.js']).pipe(sourcemaps.init()).pipe(uglify()).pipe(rename({suffix: '.min'})).pipe(sourcemaps.write()).pipe(gulp.dest('web/js')))
    // gulp.task('compile-js', () => (stream => merge2([stream.dts.pipe(gulp.dest('web/js')), stream.pipe(sourcemaps.write()).pipe(gulp.dest('web/js'))]))(gulp.src(['web/ts/*.ts', 'web/ts/**/*.ts']).pipe(sourcemaps.init()).pipe(typescript(project))))

    // gulp.task('build-css', gulp.series('clean-css', 'compile-css', 'minify-css'))
    // gulp.task('watch-css', () => gulp.watch(['web/scss/*.scss', 'web/scss/**/*.scss'], gulp.series('build-css')))
    // gulp.task('clean-css', () => del(['web/css/*.css', 'web/css/**.*.css', 'web/css/*.map', 'web/css/**.*.map']))
    // gulp.task('compile-css', () => gulp.src(['web/scss/*.scss', 'web/scss/**/*.scss']).pipe(sourcemaps.init()).pipe(sass()).pipe(sourcemaps.write()).pipe(gulp.dest('web/css')))
    // gulp.task('minify-css', () => gulp.src(['web/css/*.css', 'web/css/**/*.css', '!web/css/*.min.css', '!web/css/**/*.min.css']).pipe(sourcemaps.init()).pipe(uglifycss()).pipe(rename({suffix: '.min'})).pipe(sourcemaps.write()).pipe(gulp.dest('web/css')))

    // gulp.task('@clean', gulp.series('clean-css', 'clean-js'))
    // gulp.task('@build', gulp.series('build-css', 'build-js'))
    // gulp.task('@watch', gulp.series('watch-css', 'watch-js'))
    // gulp.task('@minify', gulp.series('minify-css', 'minify-js'))
    // gulp.task('@compile', gulp.series('compile-css', 'compile-js'))
    
}(require("del"), require('gulp'), require('merge2'), require('gulp-sass'), require('gulp-rename'), require('gulp-uglify'), require('gulp-uglifycss'), require('gulp-typescript'), require('gulp-sourcemaps'));
```
It will become confusing & hard when tasks have complex dependencies.

The file must load all, then gulp may run `task`(s).
i.e:  `gulp.task` !== `gulp.start`

**Comment by phated** [comment] 2016-05-19 02:00
This is by design.  The way you are registering tasks is an anti-pattern in gulp 4.  I recommend you use named functions if you want to use this pattern (since every function is within your closure scope).  

Duplicate of #1635

**Closed by phated** 2016-05-19 02:00 UTC

**Comment by SalathielGenese** [comment] 2016-05-19 09:06
By your answer, I guess you want me to write something like
```javascript
gulp.task('a', gulp.series(task_b)); // note task_b without quotes
gulp.task('b', function task_b() {...});
```
which will not work, following an answer I got about [javascript named funtion & javascript named expression][1].

Then, another option would be to write:
```javascript
gulp.task('a', gulp.series(task_b)); // note b without quotes
gulp.task('b', task_b);

function task_b()
{...}
```
Which becomes a heavy syntax.

> That's why my suggestion is that `gulpjs-v4` would load all tasks first, before running the specified ones... as a mean the developer work-flow writing.

   [1]: http://stackoverflow.com/questions/36941769/whats-the-scope-of-javascript-named-function-passed-as-parameter
