### ISSUE TITLE
Static files broken

### ISSUE THREAD

**Issue by cbratschi** [gulpjs/gulp#2789] opened 2024-04-08 16:03 UTC
The following code should just copy files from source to destination:

```JavaScript
gulp.src(folder + '/**')
            .pipe(gulp.dest(dstFolder))
```

However, the copied images are broken i.e. finder and VSC no longer shows them as valid image files. Same happens to font files.

### Please provide the following information:
* OS & version [e.g. MacOS Catalina 10.15.4]: macOS Sonoma 14.4.1
* node version (run `node -v`): v20.11.1
* npm version (run `npm -v`): 10.2.4
* gulp version (run `gulp -v`): 5.0.0

**Comment by yocontra** [comment] 2024-04-09 02:22
Duplicate of many other issues - see the changelog, you have to specify `encoding: false` as an option to gulp.src for binary files.

**Closed by yocontra** 2024-04-09 02:22 UTC

**Comment by cbratschi** [comment] 2024-04-09 10:17
@yocontra thanks, it works now.

The documentation just mentions "Default stream encoding to UTF-8" as breaking change but does not list any side effects or migration paths.

For others, the solution is:

```JavaScript
gulp.src(folder + '/**', {
    encoding: false
})
    .pipe(gulp.dest(dstFolder));
```

This is needed for all binary files, such as images or fonts.
