### ISSUE TITLE
[4.0] gulp.watch fails working after a single update

### ISSUE THREAD

**Issue by nmccready** [gulpjs/gulp#1658] opened 2016-05-12 20:31 UTC
Gulp 4.0 was recently changed to use `glob-watcher` instead of `chokidar` directly. With that change watch does not work on sequential updates after the first change.

There are many comments on the change set [here](https://github.com/gulpjs/gulp/commit/6c03475e1a39d18c139b4d56baa1c14a587f9f4a).

**Comment by phated** [comment] 2016-05-12 20:46
Duplicate of #1623, #1624, #1626, #1638 and #1656 - Please look through issues before opening __yet__ another issue about the exact same thing.

**Closed by phated** 2016-05-12 20:46 UTC

**Comment by alexisdiel** [comment] 2018-01-26 19:07
added the done parameter at the last task and callback at the end.

> gulp.task("reload", (done) => { browserSync.reload(); done(); });
> gulp.task("js:watch", () => gulp.watch("lib/**/*.js", gulp.series("js", "reload")));
