### ISSUE TITLE
running a default gulp task in terminal causes high CPU and battery life

### ISSUE THREAD

**Issue by jacobraccuia** [gulpjs/gulp#1426] opened 2015-12-03 08:05 UTC
I am calling $ gulp and when it runs, my battery life of my mac is considerably decreased ( about an hour and a half vs. 5 hours without running it ).  this is only if I call gulp as the constant default task and not if I manually call gulp css.

I am running El Capitan 10.11.1 on a 2.8gHZ i7 with 16gb of memory.  

Here is my file:

	var gulp = require('gulp');
	var gutil = require('gulp-util');
	var ftp = require('vinyl-ftp');
	var runSequence = require('run-sequence');
	// CSS
	var postcss = require('gulp-postcss');
	var autoprefixer = require('autoprefixer');
	var precss = require('precss');
	//var minifyCSS = require('gulp-minify-css');

	// define the default task and add the watch task to it
	gulp.task('default', ['deploy', 'css'], function() {
		gulp.watch('src/css/*.css', {debounceDelay: 2000}, ['css']);
		gulp.watch('**',  {debounceDelay: 2000}, ['deploy']);
	});

	// css
	gulp.task('css', function () {
		var processors = [
		autoprefixer({ browsers: ['> 5%'] }),
		precss
		];

		return gulp.src('src/css/*.css')
		.pipe(postcss(processors))
		.pipe(gulp.dest(''));
	});

	// FTP
	// conn data commented out

	gulp.task('reset', function(cb) { 
		runSequence('clean', 'deploy', cb);
	});

	gulp.task('deploy', function() {
	    var globs = [
	    '**',
	    ];

	    return gulp.src(globs, { base: '.', buffer: false })
	        .pipe(conn.newer('path')) // only upload newer files 
	        .pipe(conn.dest('path'))
	        .pipe(conn.mode('path', '0664'));
	    });

	gulp.task('clean', function(cb) {
		conn.rmdir('path', cb);
	});

**Comment by jonschlinkert** [comment] 2015-12-03 21:46
hey I noticed you have `watch` setup in your default task. That would cause your battery down faster than it normally would, since it continually runs in the background. The `css` task doesn't trigger watch, so you won't see the same batter consumption from running `gulp css` explicitly.

**Comment by kevdez** [comment] 2015-12-03 21:46
Your "css" task is meant to process your css files one time, whereas your "default" task depends on both the "css" and "deploy" tasks, along with 2 gulp.watch calls. Most of the processing power, if you leave the default gulp task running, is on these file watchers. They're constantly listening in for any changes made to the css files. If you leave it running, then yeah, this is the cause of the battery drain.

**Comment by jacobraccuia** [comment] 2015-12-03 23:17
So essentially, there is no way for me to run gulp watch without excessive battery strain?  I guess I understand why watching a specific file would cause strain, but why is it so much?  It's not like I'm monitoring hundreds of folders!

Is there any way to run a watch - like "gulp watch css" and have it only monitor and not strain?

**Comment by kevdez** [comment] 2015-12-04 01:15
I'm not sure what you mean by "only monitor and not strain" but I have an idea.

Since gulp is called by "gulp [list of tasks]", your "gulp watch css" would mean you have both a "watch" task and a "css" task. I think you want something like "gulp watchCSS" where you only have *one* task to watch your css. That's doable. But whether it will reduce processor use, and therefore battery use, I'm not sure.

Even as gulp is watching files, it depends on *what it does* as soon as a file changes. If you're constantly updating CSS or changing many CSS files at once, then yeah, gulp will be doing whatever actions you assigned on each modification. Say you're converting LESS and SASS to CSS each time, then that's even more processor power being used.

I would recommend watching your CPU usage, RAM, and all the processes with Activity Monitor, since you said you're on a Mac.

**Comment by contra** [comment] 2015-12-04 02:44
This is a known problem with the gulp 3.x watcher - this is fixed in gulp 4.0

**Closed by contra** 2015-12-04 02:44 UTC
